### ISSUE TITLE
[bug] panic: invalid freelist page: 9437184, page type is unknown<00>

### ISSUE THREAD

**Issue by everhopingandwaiting** [go-gitea/gitea#10494]
- Gitea version (or commit ref):   v1.12.0+dev-386-g4a2d23981 
- Git version: 2.24.1
- Operating system: docker
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [X] SQLite
  - [X] Redis
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant
- Log gist:

## Description
```json
2020/02/27 12:56:09 cmd/web.go:107:runWeb() [I] Starting Gitea on PID: 16
2020/02/27 12:56:09 ...dules/setting/git.go:91:newGit() [I] Git Version: 2.24.1, Wire Protocol Version 2 Enabled
2020/02/27 12:56:09 routers/init.go:88:GlobalInit() [T] AppPath: /app/gitea/gitea
2020/02/27 12:56:09 routers/init.go:89:GlobalInit() [T] AppWorkPath: /app/gitea
2020/02/27 12:56:09 routers/init.go:90:GlobalInit() [T] Custom path: /data/gitea
2020/02/27 12:56:09 routers/init.go:91:GlobalInit() [T] Log path: /data/gitea/log
2020/02/27 12:56:09 ...dules/setting/log.go:233:newLogService() [I] Gitea v1.12.0+dev-386-g4a2d23981 built with GNU Make 4.2.1, go1.13.8 : bindata, sqlite, sqlite_unlock_notify
panic: invalid freelist page: 9437184, page type is unknown<00>

goroutine 92 [running]:
github.com/etcd-io/bbolt.(*freelist).read(0xc002a38300, 0x7f702ee6a000)
        /go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/freelist.go:266 +0x2ab
github.com/etcd-io/bbolt.(*DB).loadFreelist.func1()
        /go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/db.go:316 +0xcf
sync.(*Once).doSlow(0xc0029b2368, 0xc002a69900)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/etcd-io/bbolt.(*DB).loadFreelist(0xc0029b2200)
        /go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/db.go:309 +0x6a
github.com/etcd-io/bbolt.Open(0xc00332ea80, 0x26, 0x180, 0xc002a69ae8, 0x4b7eb40, 0x0, 0x0)
        /go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/db.go:286 +0x35d
github.com/blevesearch/bleve/index/store/boltdb.New(0x365ea20, 0x4b7c500, 0xc000b479b0, 0x6, 0xc000858d90, 0xc002a69c10, 0x50)
        /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/store/boltdb/store.go:83 +0x309
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Open(0xc002a38280, 0x0, 0x0)
        /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:308 +0x103
github.com/blevesearch/bleve.openIndexUsing(0xc0002a13a0, 0x20, 0x0, 0xc00017c1c0, 0x0, 0x0)
        /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index_impl.go:174 +0x516
github.com/blevesearch/bleve.Open(...)
        /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.go:286
code.gitea.io/gitea/modules/indexer/code.openIndexer(0xc0002a13a0, 0x20, 0x5, 0x414708, 0x20, 0x1ec28c0, 0x1)
        /go/src/code.gitea.io/gitea/modules/indexer/code/bleve.go:81 +0xbf
code.gitea.io/gitea/modules/indexer/code.(*BleveIndexer).init(0xc003321ea0, 0xc003321ea0, 0x22527ec, 0x2e)
        /go/src/code.gitea.io/gitea/modules/indexer/code/bleve.go:235 +0x44
code.gitea.io/gitea/modules/indexer/code.NewBleveIndexer(...)
        /go/src/code.gitea.io/gitea/modules/indexer/code/bleve.go:228
code.gitea.io/gitea/modules/indexer/code.Init.func2(0xc002a3f660, 0xc0029f3980)
        /go/src/code.gitea.io/gitea/modules/indexer/code/indexer.go:67 +0x1b1
created by code.gitea.io/gitea/modules/indexer/code.Init
        /go/src/code.gitea.io/gitea/modules/indexer/code/indexer.go:64 +0x133
```
...

## app.ini
```
APP_NAME = jyao
RUN_MODE = prod
RUN_USER = git

[repository]
ROOT = /data/git/repositories

[repository.local]
LOCAL_COPY_PATH = /data/gitea/tmp/local-repo

[repository.upload]
TEMP_PATH = /data/gitea/uploads
FILE_MAX_SIZE = 5
; Max number of files per upload. Defaults to 5
MAX_FILES = 5

[server]
PROTOCAL         = https
APP_DATA_PATH    = /data/gitea
DOMAIN           = 192.168.0.23
SSH_DOMAIN       = %(DOMAIN)s
HTTP_PORT        = 10081
DISABLE_SSH      = false
SSH_PORT         = 10023
SSH_LISTEN_PORT  = 22
LFS_START_SERVER = true
LFS_CONTENT_PATH = /data/git/lfs
LFS_JWT_SECRET   = NVSLf5cVwwL6oA0hAFlDJM-RW0ExlG3xnppaoQu1HTo
OFFLINE_MODE     = false
ENABLE_GZIP      = true
DISABLE_ROUTER_LOG = true

[database]
PATH     = /data/gitea/gitea.db
DB_TYPE  = sqlite3
HOST     = mysql-server:3306
NAME     = gitea
USER     = root
PASSWD   = rooroot@!@#
SCHEMA   = 
SSL_MODE = disable
CHARSET  = utf8

[indexer]

ISSUE_INDEXER_TYPE = db
ISSUE_INDEXER_CONN_STR = addrs=redis-server:6379 db=0

ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve
ISSUE_INDEXER_QUEUE_TYPE = redis
ISSUE_INDEXER_QUEUE_CONN_STR = addrs=redis-server:6379 db=0
REPO_INDEXER_ENABLED = true

REPO_INDEXER_INCLUDE =
REPO_INDEXER_EXCLUDE = target/**,dist/**


[cache]
ENABLED = true
ADAPTER = redis
HOST    = network=tcp,addr=redis-server:6379,,db=0,pool_size=100,idle_timeout=180

[session]
; PROVIDER_CONFIG = /data/gitea/sessions
; PROVIDER        = file
PROVIDER          = redis
PROVIDER_CONFIG   = network=tcp,addr=redis-server:6379,,db=0,pool_size=100,idle_timeout=180
COOKIE_NAME       = i_like_


[picture]
AVATAR_UPLOAD_PATH            = /data/gitea/avatars
REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
DISABLE_GRAVATAR              = false
ENABLE_FEDERATED_AVATAR       = true

[attachment]
PATH = /data/gitea/attachments
ALLOWED_TYPES = */*
MAX_SIZE = 1024
MAX_FILES = 20

[log]
ROOT_PATH = /data/gitea/log
MODE      = file
LEVEL     = info

[security]
INSTALL_LOCK   = true
SECRET_KEY     = uSUJgEofU58bRn7i3ne9tbHFeFSAFqkD5nhE6bVrI9
INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..K8MNWvJktzc38RATTru095OuGrLchVhjLcHC3q0mAKQ

[service]
DISABLE_REGISTRATION              = false
REQUIRE_SIGNIN_VIEW               = false
REGISTER_EMAIL_CONFIRM            = false
ENABLE_NOTIFY_MAIL                = false
ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
ENABLE_CAPTCHA                    = false
DEFAULT_KEEP_EMAIL_PRIVATE        = false
DEFAULT_ALLOW_CREATE_ORGANIZATION = true
DEFAULT_ENABLE_TIMETRACKING       = true
NO_REPLY_ADDRESS                  = noreply.localhost

[oauth2]
JWT_SECRET = -zVWM

[mailer]
ENABLED = false

[openid]
ENABLE_OPENID_SIGNIN = true
ENABLE_OPENID_SIGNUP = true

[ui]
DEFAULT_SHOW_FULL_NAME = true
SEARCH_REPO_DESCRIPTION = true
USE_SERVICE_WORKER      = true

[webhook]
SKIP_TLS_VERIFY=true

[task]
QUEUE_TYPE = redis
QUEUE_CONN_STR = addrs=redis-server:6379 db=0
[other]
; SHOW_FOOTER_BRANDING = false
SHOW_FOOTER_VERSION = false

```
## Screenshots

![image](https://user-images.githubusercontent.com/6021724/75416592-9ab1c080-5969-11ea-8dcb-f17e871ca060.png)

**Comment by everhopingandwaiting** [comment]
```
rm -fr /data/gitea/indexers
```
it works
why ?

**Comment by zeripath** [comment]
*Sigh* when will libraries learn that `panic` is absolutely not acceptable. There's not much we can do about the error - that being said we can make the information a bit better - see #10534

**Comment by guillep2k** [comment]
This should be resolved by rebuilding the indexes, as hinted by #10534.

May we close this?

**Comment by everhopingandwaiting** [comment]
yes, I will cols it now!  thanks
