### ISSUE TITLE
/metrics causes proccess to crash with sig 15

### ISSUE THREAD

**Issue by borisovano** [go-gitea/gitea#10720]
- Gitea version (or commit ref):
Gitea v1.11.0+dev-448-g59fc29db3 built with GNU Make 4.2.1, go1.13.5

- Operating system: 
Mac / Catalina + Docker with suggested compose.yml

- Database (use `[x]`):
The default with Docker installation 
- Can you reproduce the bug at https://try.gitea.io:
No

- Log gist:
```
server_1  | [Macaron] 2020-03-12 11:48:57: Started GET /metrics for 172.21.0.1
server_1  | panic: runtime error: invalid memory address or nil pointer dereference
server_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0xb4c956]
server_1  | 
server_1  | goroutine 1408 [running]:
server_1  | xorm.io/xorm.(*Session).Init(0xc002cf1180)
server_1  |     /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/session.go:94 +0x1e6
server_1  | xorm.io/xorm.(*Engine).NewSession(...)
server_1  |     /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/engine.go:317
server_1  | xorm.io/xorm.(*Engine).Where(0x0, 0x1983f20, 0x3277220, 0x0, 0x0, 0x0, 0x0)
server_1  |     /go/src/code.gitea.io/gitea/vendor/xorm.io/xorm/engine.go:601 +0x56
server_1  | code.gitea.io/gitea/models.countUsers(0x32f59c0, 0x0, 0x0)
server_1  |     /go/src/code.gitea.io/gitea/models/user.go:923 +0x61
server_1  | code.gitea.io/gitea/models.CountUsers(...)
server_1  |     /go/src/code.gitea.io/gitea/models/user.go:930
server_1  | code.gitea.io/gitea/models.GetStatistic(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
server_1  |     /go/src/code.gitea.io/gitea/models/models.go:204 +0x5c
server_1  | code.gitea.io/gitea/modules/metrics.Collector.Collect(0xc0036863f0, 0xc003686460, 0xc0036864d0, 0xc003686540, 0xc0036865b0, 0xc003687730, 0xc0036877a0, 0xc003687810, 0xc003687880, 0xc0036878f0, ...)
server_1  |     /go/src/code.gitea.io/gitea/modules/metrics/collector.go:187 +0x37
server_1  | github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
server_1  |     /go/src/code.gitea.io/gitea/vendor/github.com/prometheus/client_golang/prometheus/registry.go:442 +0x19d
server_1  | created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
server_1  |     /go/src/code.gitea.io/gitea/vendor/github.com/prometheus/client_golang/prometheus/registry.go:534 +0xe12
server_1  | Received signal 15; terminating.
```
## Description

Running on my dev machine via vanilla docker compose installation
Added metrics section + ENABLED, no TOKEN
Access localhost:3000/metrics
Crash (trace + log above)

**Comment by zeripath** [comment]
Is this still, rather embarrassingly if so, broken?

**Comment by techknowlogick** [comment]
Unable to replicate on master branch. Closing. Please re-open if still encountering issue.
