### ISSUE TITLE
Migration from gogs with SQlite seems to be broken

### ISSUE THREAD

**Issue by tboerger** [go-gitea/gitea#124]
@vtolstov ran into an issue while tried to migrate the gogs sqlite database to current develop branch of gitea which results in something like this:

```
Jul 24 13:13:44 selfip.ru gitea[6305]: 2015/07/24 13:13:44 [install.go:68 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: near "MODIFY": syntax error
```

**Comment by vtolstov** [comment]
after fixing sqlite i have error in templates

```
Jul 24 20:21:29 selfip.ru gitea[14312]: panic: template: repo/issue/list:10: unexpected . after term "."
Jul 24 20:21:29 selfip.ru gitea[14312]: goroutine 1 [running]:
Jul 24 20:21:29 selfip.ru gitea[14312]: html/template.Must(0x0, 0x7ff9375ab028, 0xc208175d30, 0x0)
Jul 24 20:21:29 selfip.ru gitea[14312]: /usr/lib64/go/src/html/template/template.go:330 +0x52
Jul 24 20:21:29 selfip.ru gitea[14312]: github.com/Unknwon/macaron.compile(0xc208321360, 0x1a, 0x0, 0x0, 0xc208321380, 0x2, 0x2, 0xc208025590, 0x1, 0x1, ...)
Jul 24 20:21:29 selfip.ru gitea[14312]: /var/tmp/paludis/build/dev-util-gitea-scm/work/gitea-scm/gopath/src/github.com/Unknwon/macaron/render.go:276 +0x6a5
Jul 24 20:21:29 selfip.ru gitea[14312]: github.com/Unknwon/macaron.(*templateSet).Set(0xc20833c000, 0xe4cbb0, 0x7, 0xc2081c8700, 0x0)
Jul 24 20:21:29 selfip.ru gitea[14312]: /var/tmp/paludis/build/dev-util-gitea-scm/work/gitea-scm/gopath/src/github.com/Unknwon/macaron/render.go:301 +0x4d
Jul 24 20:21:29 selfip.ru gitea[14312]: github.com/Unknwon/macaron.renderHandler(0xc208321360, 0x1a, 0x0, 0x0, 0xc208321380, 0x2, 0x2, 0xc208025590, 0x1, 0x1, ...)
Jul 24 20:21:29 selfip.ru gitea[14312]: /var/tmp/paludis/build/dev-util-gitea-scm/work/gitea-scm/gopath/src/github.com/Unknwon/macaron/render.go:368 +0x214
Jul 24 20:21:29 selfip.ru gitea[14312]: github.com/Unknwon/macaron.Renderer(0xc2081b6f98, 0x1, 0x1, 0x0, 0x0)
Jul 24 20:21:29 selfip.ru gitea[14312]: /var/tmp/paludis/build/dev-util-gitea-scm/work/gitea-scm/gopath/src/github.com/Unknwon/macaron/render.go:405 +0x1f1
Jul 24 20:21:29 selfip.ru gitea[14312]: github.com/go-gitea/gitea/cmd.newMacaron(0xc20817a2d0)
Jul 24 20:21:29 selfip.ru gitea[14312]: /var/tmp/paludis/build/dev-util-gitea-scm/work/gitea-scm/gopath/src/github.com/go-gitea/gitea/cmd/web.go:127 +0x76a
Jul 24 20:21:29 selfip.ru gitea[14312]: github.com/go-gitea/gitea/cmd.runWeb(0xc20817a2d0)
Jul 24 20:21:29 selfip.ru gitea[14312]: /var/tmp/paludis/build/dev-util-gitea-scm/work/gitea-scm/gopath/src/github.com/go-gitea/gitea/cmd/web.go:186 +0xc5
Jul 24 20:21:29 selfip.ru gitea[14312]: github.com/codegangsta/cli.Command.Run(0xe79950, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xedf9f0, 0x16, 0x1021470, ...)
Jul 24 20:21:29 selfip.ru gitea[14312]: /var/tmp/paludis/build/dev-util-gitea-scm/work/gitea-scm/gopath/src/github.com/codegangsta/cli/command.go:127 +0x1055
Jul 24 20:21:29 selfip.ru gitea[14312]: github.com/codegangsta/cli.(*App).Run(0xc2080b2700, 0xc20800a140, 0x4, 0x4, 0x0, 0x0)
Jul 24 20:21:29 selfip.ru gitea[14312]: /var/tmp/paludis/build/dev-util-gitea-scm/work/gitea-scm/gopath/src/github.com/codegangsta/cli/app.go:159 +0xc32
Jul 24 20:21:29 selfip.ru gitea[14312]: main.main()
```

**Comment by vtolstov** [comment]
does this right fix? in case of sqlite we don't modify columns

**Comment by lunny** [comment]
Since sqlite3 does not support modify column type, so we have to drop column and add new one? But maybe that will lost some data.

**Comment by vtolstov** [comment]
@lunny right way is rename table, create new table, select from all table and insert into new. After that - drop old table.

**Comment by lunny** [comment]
OKay. Let me try to do it.

**Comment by lunny** [comment]
Please recheck. @vtolstov

**Comment by vtolstov** [comment]
Looks good,but how about this:
Old table have int column
New table have varchar column
Does acceptable insert 0 to varchar that needs to be null ?

**Comment by lunny** [comment]
I think this compatible problem could be resolved via xorm or our codes.

**Comment by vtolstov** [comment]
OK,fine. Thanks for fix
01 авг. 2015 г. 2:55 пользователь "Lunny Xiao" <notifications@github.com>
написал:

**Comment by lunny** [comment]
OK. Let us close this currently.
