### ISSUE TITLE
[Bug] doctor: crash if not able to open doctor.log

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#12706]
Version v1.12.4

`sudo -u gitea gitea doctor --all` executed will just crash with:

```
panic: Failed to create sublogger (doctor): open doctor.log: permission denied

goroutine 1 [running]:
code.gitea.io/gitea/modules/log.NewLogger(0x3e8, 0x20d618a, 0x6, 0x20be030, 0x4, 0xc000192370, 0x42, 0x1fa9d20)
	/home/user/aports/community/gitea/src/src/code.gitea.io/gitea/modules/log/log.go:48 +0x1ad
code.gitea.io/gitea/cmd.runDoctor(0xc0003c8840, 0x0, 0xc0003c86e0)
	/home/user/aports/community/gitea/src/src/code.gitea.io/gitea/cmd/doctor.go:149 +0x1aa
github.com/urfave/cli.HandleAction(0x1d49880, 0x2283168, 0xc0003c8840, 0xc00035ba00, 0x0)
	/home/user/aports/community/gitea/src/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:490 +0x82
github.com/urfave/cli.Command.Run(0x20d618a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x218d96a, 0x11, 0x0, ...)
	/home/user/aports/community/gitea/src/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:210 +0x9fb
github.com/urfave/cli.(*App).Run(0xc001222340, 0xc0000a2150, 0x3, 0x3, 0x0, 0x0)
	/home/user/aports/community/gitea/src/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:255 +0x768
main.main()
	/home/user/aports/community/gitea/src/src/code.gitea.io/gitea/main.go:109 +0x972
```

## I expect:
... that doctor tell me what I have to change to be able to execute it

**Comment by 6543** [comment]
... or print Warning: `could not write log - do not have permission to write doctor.log in current folder
check only posible ....`
and start checking if there is any probel (but --fix mode is disabled)

**Comment by 6543** [comment]
no stale ... there is  #12264
