### ISSUE TITLE
Gitea fails to build

### ISSUE THREAD

**Issue by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [go-gitea/gitea#13763]
- Gitea version (or commit ref): `Gitea version 1.14.0+dev-281-ge8a6c425e built with GNU Make 4.3, go1.15.5 : bindata, sqlite, sqlite_unlock_notify`
- Git version: `git version 2.29.2.576.ga3fc446d84`
- Operating system: Arch Linux
- Built from
  - [x] source
- Run with
  - [x] systemd
- Database:
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] No
- Log gist:

```log
nebula gitea-src (master) %  TAGS="bindata sqlite sqlite_unlock_notify" make build
rm -rf public/js public/css public/fonts public/img/webpack public/serviceworker.js
npx webpack --hide-modules --display-entrypoints=false
/home/user/gitea-src/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

TypeError: isPlainObject is not a function
    at isExtendable (/home/user/gitea-src/node_modules/mixin-deep/node_modules/is-extendable/index.js:13:10)
    at isObject (/home/user/gitea-src/node_modules/mixin-deep/index.js:46:10)
    at mixinDeep (/home/user/gitea-src/node_modules/mixin-deep/index.js:10:9)
    at Snapdragon.Base.initBase (/home/user/gitea-src/node_modules/base/index.js:70:20)
    at Snapdragon.Base (/home/user/gitea-src/node_modules/base/index.js:50:10)
    at new Snapdragon (/home/user/gitea-src/node_modules/snapdragon/index.js:23:8)
    at Object.utils.instantiate (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/lib/utils.js:43:18)
    at parse (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:736:28)
    at memoize (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.parse (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:745:10)
    at create (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:686:44)
    at /home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:695:16
    at memoize (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.create (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:684:10)
    at makeRe (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:581:29)
    at memoize (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.makeRe (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:598:10)
    at Function.matcher (/home/user/gitea-src/node_modules/findup-sync/node_modules/micromatch/index.js:485:23)
    at matchFile (/home/user/gitea-src/node_modules/findup-sync/index.js:60:20)
    at lookup (/home/user/gitea-src/node_modules/findup-sync/index.js:43:13)
    at module.exports (/home/user/gitea-src/node_modules/findup-sync/index.js:26:12)
    at module.exports (/home/user/gitea-src/node_modules/webpack-cli/bin/utils/convert-argv.js:73:31)
    at /home/user/gitea-src/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/user/gitea-src/node_modules/yargs/yargs.js:576:18)
    at /home/user/gitea-src/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/user/gitea-src/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
npm ERR! code 1
npm ERR! path /home/user/gitea-src
npm ERR! command failed
npm ERR! command sh -c webpack --hide-modules '--display-entrypoints=false'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-11-30T18_04_10_857Z-debug.log
make: *** [Makefile:654: public/js/index.js] Error 1
```
```log
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'webpack',
0 verbose cli   '--hide-modules',
0 verbose cli   '--display-entrypoints=false'
0 verbose cli ]
1 info using npm@7.0.5
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/user/gitea-src/.npmrc Completed in 4ms
9 timing config:load:project Completed in 5ms
10 timing config:load:file:/root/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 2ms
18 timing config:load Completed in 18ms
19 verbose npm-session c836e30a5b8603e4
20 timing npm:load Completed in 31ms
21 timing command:exec Completed in 638ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:63:27)
22 verbose stack     at ChildProcess.emit (node:events:376:20)
22 verbose stack     at maybeClose (node:internal/child_process:1055:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
23 verbose cwd /home/user/gitea-src
24 verbose Linux 5.9.11-arch2-1
25 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "webpack" "--hide-modules" "--display-entrypoints=false"
26 verbose node v15.3.0
27 verbose npm  v7.0.5
28 error code 1
29 error path /root/gitea-src
30 error command failed
31 error command sh -c webpack --hide-modules '--display-entrypoints=false'
32 verbose exit 1
```

## Description
Gitea fails to build after updating sources to commit merged by https://github.com/go-gitea/gitea/pull/13752.
This issue is not present prior to the subject commit.
However, I was able to build Gitea on Fedora 33 successfully so it's a bit weird.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
alright I was able to solve this removing `~/.npm` and `~/gitea-src/node_modules`

```sh
rm -rfv /home/user/.npm
rm -rfv /home/user/gitea-src/node_modules
```
Gitea now builds fine.
Don't know what the error was about, though.

Feel free to close this.

**Comment by wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf** [comment]
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf
> 
> `TAGS="bindata sqlite sqlite_unlock_notify" make clean-all build` - if you like to start "clean"

that's actually a good idea... thanks @6543
