### ISSUE TITLE
Unable to build frontend.

### ISSUE THREAD

**Issue by miou-gh** [go-gitea/gitea#14520]
- Gitea version (or commit ref): 25b6255b924c30a2bab066c0465d146a34021245
- Git version: 2.30.0
- Operating system: Manjaro Linux
  

  
  
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
- Log gist:

## Description

The following command (as is listed in the README) results in the following error, this is after running pacman -Syu.

```
[allie@allie-virtualbox gitea]$ TAGS="bindata sqlite sqlite_unlock_notify" make build
rm -rf public/js public/css public/fonts public/img/webpack public/serviceworker.js
npx webpack
/home/allie/Gitea/gitea/node_modules/webpack/node_modules/source-map/lib/util.js:24
    throw new Error('"' + aName + '" is a required argument.');
          ^

Error: "version" is a required argument.
    at Object.getArg (/home/allie/Gitea/gitea/node_modules/webpack/node_modules/source-map/lib/util.js:24:11)
    at new BasicSourceMapConsumer (/home/allie/Gitea/gitea/node_modules/webpack/node_modules/source-map/lib/source-map-consumer.js:294:22)
    at new SourceMapConsumer (/home/allie/Gitea/gitea/node_modules/webpack/node_modules/source-map/lib/source-map-consumer.js:22:7)
    at SourceMapSource.node (/home/allie/Gitea/gitea/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:193:4)
    at exports.getSourceAndMap (/home/allie/Gitea/gitea/node_modules/webpack/node_modules/webpack-sources/lib/helpers.js:20:27)
    at SourceMapSource.sourceAndMap (/home/allie/Gitea/gitea/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:184:10)
    at getTaskForFile (/home/allie/Gitea/gitea/node_modules/webpack/lib/SourceMapDevToolPlugin.js:78:30)
    at /home/allie/Gitea/gitea/node_modules/webpack/lib/SourceMapDevToolPlugin.js:266:22
    at /home/allie/Gitea/gitea/node_modules/webpack/lib/Cache.js:93:5
    at Hook.eval [as callAsync] (eval at create (/home/allie/Gitea/gitea/node_modules/tapable/lib/HookCodeFactory.js:1:1), <anonymous>:6:1)
    at Cache.get (/home/allie/Gitea/gitea/node_modules/webpack/lib/Cache.js:75:18)
    at ItemCacheFacade.get (/home/allie/Gitea/gitea/node_modules/webpack/lib/CacheFacade.js:116:15)
    at /home/allie/Gitea/gitea/node_modules/webpack/lib/SourceMapDevToolPlugin.js:217:18
    at arrayEach (/home/allie/Gitea/gitea/node_modules/neo-async/async.js:2405:9)
    at Object.each (/home/allie/Gitea/gitea/node_modules/neo-async/async.js:2846:9)
    at /home/allie/Gitea/gitea/node_modules/webpack/lib/SourceMapDevToolPlugin.js:204:15
make: *** [Makefile:663: public/js/index.js] Error 1
```

...

**Comment by bagasme** [comment]
@atillabyte Seems like you're running latest node from your distro (15.7.0). Please try building with latest LTS instead (v14.15.4).
I don't have problem building that commit with node LTS.

**Comment by bagasme** [comment]
@atillabyte I can't reproduce this issue with node 15.7.0, with your mentioned commit and current latest master (0e0424c8ecaf6fa3cdd1fcfc154f188014c63dd8). Perhaps because of node cache.

**Comment by atillabyte** [comment]
I tried manually purging the node cache and that didn't do, however upgrading `css-minimizer-webpack-plugin` to the latest `1.2.0` solved it. ^^

**Comment by atillabyte** [comment]
Apparently other people have also had this issue this month. https://github.com/webpack/webpack/issues/12229

**Comment by 6543** [comment]
@atillabyte If you like, you can file up a pull :)
