### ISSUE TITLE
New wiki filename encoding is incompatible with old version and causes error 500

### ISSUE THREAD

**Issue by typeless** [go-gitea/gitea#1483]
- Gitea version (or commit ref):
Gitea version 1.1.0+115-g54f0293 built with: bindata, sqlite

- Git version:
git version 2.7.4

- Operating system:
Ubuntu 16.04.2 LTS

- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
The `debug.PrintStack` is added by myself for showing the call trace of the internal error. It's not a 'crash'.
```
Apr 11 09:52:03 DIR-101 gitea[27199]: goroutine 1638 [running]:
Apr 11 09:52:03 DIR-101 gitea[27199]: runtime/debug.Stack(0x11ec34b, 0x4, 0x18df918)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/tools/go/src/runtime/debug/stack.go:24 +0x87
Apr 11 09:52:03 DIR-101 gitea[27199]: runtime/debug.PrintStack()
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/tools/go/src/runtime/debug/stack.go:16 +0x34
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/modules/context.(*Context).Handle(0xc421408480, 0x1f4, 0x18f09cf, 0xe, 0x23be5e0, 0xc421fcd370)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/modules/context/context.go:105 +0x37b
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/routers/repo.DeleteWikiPagePost(0xc421408480)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/routers/repo/wiki.go:514 +0x418
Apr 11 09:52:03 DIR-101 gitea[27199]: reflect.Value.call(0x1766d40, 0x193fa48, 0x13, 0x18dd022, 0x4, 0xc42165d2c0, 0x1, 0x1, 0x193fa48, 0x1766d78, ...)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/tools/go/src/reflect/value.go:434 +0xa74
Apr 11 09:52:03 DIR-101 gitea[27199]: reflect.Value.Call(0x1766d40, 0x193fa48, 0x13, 0xc42165d2c0, 0x1, 0x1, 0x0, 0x0, 0x0)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/tools/go/src/reflect/value.go:302 +0xc1
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/github.com/go-macaron/inject.(*injector).callInvoke(0xc421a6c960, 0x1766d40, 0x193fa48, 0x23dec40, 0x1766d40, 0x1, 0x0, 0x0, 0x0, 0x478512, ...)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 +0x24b
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc421a6c960, 0x1766d40, 0x193fa48, 0x0, 0x0, 0x0, 0x0, 0x0)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 +0x109
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*Context).run(0xc420dfc510)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 +0x10d
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*Context).Next(0xc420dfc510)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 +0x7b
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/github.com/go-macaron/session.Sessioner.func1(0xc420dfc510)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/session/session.go:186 +0x51b
Apr 11 09:52:03 DIR-101 gitea[27199]: reflect.Value.call(0x1767300, 0xc42162cbe0, 0x13, 0x18dd022, 0x4, 0xc421a6cae0, 0x1, 0x1, 0xc42162cbe0, 0x1767338, ...)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/tools/go/src/reflect/value.go:434 +0xa74
Apr 11 09:52:03 DIR-101 gitea[27199]: reflect.Value.Call(0x1767300, 0xc42162cbe0, 0x13, 0xc421a6cae0, 0x1, 0x1, 0x0, 0x0, 0x0)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/tools/go/src/reflect/value.go:302 +0xc1
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/github.com/go-macaron/inject.(*injector).callInvoke(0xc421a6c960, 0x1767300, 0xc42162cbe0, 0x23dec40, 0x1767300, 0x1, 0x0, 0x0, 0x0, 0x478512, ...)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 +0x24b
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc421a6c960, 0x1767300, 0xc42162cbe0, 0x0, 0x0, 0x0, 0x0, 0x0)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 +0x109
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*Context).run(0xc420dfc510)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 +0x10d
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*Context).Next(0xc420dfc510)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 +0x7b
Apr 11 09:52:03 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.Recovery.func1(0xc420dfc510, 0xc4200154f0)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/recovery.go:161 +0x6d
Apr 11 09:52:03 DIR-101 gitea[27199]: reflect.Value.call(0x17851e0, 0x1940f80, 0x13, 0x18dd022, 0x4, 0xc421ef8c00, 0x2, 0x2, 0x1940f80, 0x1785218, ...)
Apr 11 09:52:03 DIR-101 gitea[27199]:         /home/mura/tools/go/src/reflect/value.go:434 +0xa74
Apr 11 09:52:03 DIR-101 gitea[27199]: reflect.Value.Call(0x17851e0, 0x1940f80, 0x13, 0xc421ef8c00, 0x2, 0x2, 0x88, 0x100, 0x88)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/tools/go/src/reflect/value.go:302 +0xc1
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/github.com/go-macaron/inject.(*injector).callInvoke(0xc421a6c960, 0x17851e0, 0x1940f80, 0x23dec40, 0x17851e0, 0x2, 0xc4204a0ea0, 0xc4200154f0, 0xc421ab4f88, 0x478512, ...)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 +0x24b
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc421a6c960, 0x17851e0, 0x1940f80, 0x0, 0x0, 0x0, 0x1e8d6de621ab5078, 0xed07e2dbf)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 +0x109
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*Context).run(0xc420dfc510)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 +0x10d
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*Context).Next(0xc420dfc510)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:104 +0x7b
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.Logger.func1(0xc420dfc510, 0xc4200154f0)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:43 +0x3ca
Apr 11 09:52:04 DIR-101 gitea[27199]: reflect.Value.call(0x17851e0, 0x1940f60, 0x13, 0x18dd022, 0x4, 0xc421ef8bd0, 0x2, 0x2, 0x1940f60, 0x1785218, ...)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/tools/go/src/reflect/value.go:434 +0xa74
Apr 11 09:52:04 DIR-101 gitea[27199]: reflect.Value.Call(0x17851e0, 0x1940f60, 0x13, 0xc421ef8bd0, 0x2, 0x2, 0xc4219ac028, 0xc421ab58e0, 0x10)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/tools/go/src/reflect/value.go:302 +0xc1
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/github.com/go-macaron/inject.(*injector).callInvoke(0xc421a6c960, 0x17851e0, 0x1940f60, 0x23dec40, 0x17851e0, 0x2, 0x3, 0x2c, 0x4539a4, 0x478512, ...)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 +0x24b
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/github.com/go-macaron/inject.(*injector).Invoke(0xc421a6c960, 0x17851e0, 0x1940f60, 0xc4219ac240, 0xc421501e00, 0x80, 0x45d6f0, 0xc420dfc510)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 +0x109
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*Context).run(0xc420dfc510)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:113 +0x10d
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*Router).Handle.func1(0x23c8a20, 0xc42191a000, 0xc420b58500, 0xc421ef8b40)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:184 +0x466
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*Router).ServeHTTP(0xc4200154a0, 0x23c8a20, 0xc42191a000, 0xc420b58500)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:288 +0x257
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/gopkg.in/macaron%2ev1.(*Macaron).ServeHTTP(0xc4208d1780, 0x23c8a20, 0xc42191a000, 0xc420b58500)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/macaron.go:177 +0x154
Apr 11 09:52:04 DIR-101 gitea[27199]: code.gitea.io/gitea/vendor/github.com/gorilla/context.ClearHandler.func1(0x23c8a20, 0xc42191a000, 0xc420b58500)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/devel/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 +0xa3
Apr 11 09:52:04 DIR-101 gitea[27199]: net/http.HandlerFunc.ServeHTTP(0xc4216d23a0, 0x23c8a20, 0xc42191a000, 0xc420b58500)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/tools/go/src/net/http/server.go:1942 +0x52
Apr 11 09:52:04 DIR-101 gitea[27199]: net/http.serverHandler.ServeHTTP(0xc4214f9c30, 0x23c8a20, 0xc42191a000, 0xc420b58500)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/tools/go/src/net/http/server.go:2568 +0xbd
Apr 11 09:52:04 DIR-101 gitea[27199]: net/http.(*conn).serve(0xc420da7360, 0x23ca120, 0xc420dfe180)
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/tools/go/src/net/http/server.go:1825 +0x71b
Apr 11 09:52:04 DIR-101 gitea[27199]: created by net/http.(*Server).Serve
Apr 11 09:52:04 DIR-101 gitea[27199]:         /home/mura/tools/go/src/net/http/server.go:2668 +0x360
Apr 11 09:52:04 DIR-101 gitea[27199]: [Macaron] 2017-04-11 09:52:03: Completed /mura/test/wiki/%e4%b8%ad%e6%96%87%e6%a8%99%e9%a1%8c%e6%b8%ac%e8%a9%a6/delete 500 Internal Server Error in 3.708851598s
```
## Description
My colleague has a wiki page with some non-ascii-characters (chinese characters) in the title. The wiki filename was stored as-is but in the latest version they are stored with the URL (percent) encoding. When we tried to save the edits of the page, a "500" internal error occurred.
...

**Comment by typeless** [comment]
Let me try to fix the repo manually.
