### ISSUE TITLE
SIGSEGV when testing webhook

### ISSUE THREAD

**Issue by tomas-kulhanek** [go-gitea/gitea#1500]
- Gitea version (or commit ref): 1.1.0+107-g410af69
- Git version: 1.8.3.1
- Operating system: CentOS Linux release 7.3.1611 (Core)
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
```
[Macaron] 2017-04-16 21:38:11: Completed /commerce/rlsManagement/settings/hooks/2/test 200 OK in 94.319361ms
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f310050e60d]

runtime stack:
runtime.throw(0x1415360, 0x2a)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 2688 [syscall, locked to thread]:
runtime.cgocall(0x1060ec0, 0xc4205825d8, 0x1413610)
        /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420582598 sp=0xc420582558
net._C2func_getaddrinfo(0x7f30e80008c0, 0x0, 0xc421030ae0, 0xc4218edf70, 0x0, 0x0, 0x0)
        net/_obj/_cgo_gotypes.go:86 +0x68 fp=0xc4205825d8 sp=0xc420582598
net.cgoLookupIPCNAME.func2(0x7f30e80008c0, 0x0, 0xc421030ae0, 0xc4218edf70, 0xc4205029c0, 0x4, 0xc420582698)
        /usr/local/go/src/net/cgo_unix.go:151 +0x171 fp=0xc420582638 sp=0xc4205825d8
net.cgoLookupIPCNAME(0xc421edd780, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:151 +0x1bd fp=0xc420582738 sp=0xc420582638
net.cgoIPLookup(0xc420ea0c60, 0xc421edd780, 0x8)
        /usr/local/go/src/net/cgo_unix.go:203 +0x4d fp=0xc4205827c8 sp=0xc420582738
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4205827d0 sp=0xc4205827c8
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:213 +0xb4

goroutine 1 [select, 8 minutes]:
code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp.Serve(0xc42074f3f8, 0x1, 0x1, 0xac26b1, 0x12e1680)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp/http.go:162 +0x5e6
code.gitea.io/gitea/cmd.runHTTP(0xc421576a80, 0xa, 0x1d654a0, 0xc42157b700, 0x0, 0xc421576a80)
        /srv/app/src/code.gitea.io/gitea/cmd/web_graceful.go:21 +0xc7
code.gitea.io/gitea/cmd.runWeb(0xc42044ab40, 0x0, 0x0)
        /srv/app/src/code.gitea.io/gitea/cmd/web.go:701 +0x1c35
code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0x1279480, 0x142da58, 0xc42044ab40, 0xc4203d7000, 0x0)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xb9
code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x13cf7c2, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13f6189, 0x16, 0x0, ...)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0xb4b
code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc42040aea0, 0xc42000c140, 0x2, 0x2, 0x0, 0x0)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x65f
main.main()
        /srv/app/src/code.gitea.io/gitea/main.go:44 +0x3cd

goroutine 17 [syscall, 8 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 11 [select, 8 minutes]:
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.AnalysisWorker(0xc4200558c0, 0xc420055920)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.NewAnalysisQueue
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 10 [select, 8 minutes]:
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.AnalysisWorker(0xc4200558c0, 0xc420055920)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.NewAnalysisQueue
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 9 [select]:
code.gitea.io/gitea/modules/log.(*Logger).StartLogger(0xc42004a820)
        /srv/app/src/code.gitea.io/gitea/modules/log/log.go:261 +0x142
created by code.gitea.io/gitea/modules/log.newLogger
        /srv/app/src/code.gitea.io/gitea/modules/log/log.go:191 +0xcf

goroutine 12 [select, 8 minutes]:
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.AnalysisWorker(0xc4200558c0, 0xc420055920)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.NewAnalysisQueue
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 13 [select, 8 minutes]:
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.AnalysisWorker(0xc4200558c0, 0xc420055920)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.NewAnalysisQueue
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 18 [syscall, 8 minutes]:
os/signal.signal_recv(0x4f849b)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 15 [chan receive, 8 minutes]:
code.gitea.io/gitea/modules/notification.(*notificationService).Run(0x2521610)
        /srv/app/src/code.gitea.io/gitea/modules/notification/notification.go:37 +0x63
created by code.gitea.io/gitea/modules/notification.init.1
        /srv/app/src/code.gitea.io/gitea/modules/notification/notification.go:31 +0x41

goroutine 19 [select]:
code.gitea.io/gitea/modules/log.(*Logger).StartLogger(0xc42046f7c0)
        /srv/app/src/code.gitea.io/gitea/modules/log/log.go:261 +0x142
created by code.gitea.io/gitea/modules/log.newLogger
        /srv/app/src/code.gitea.io/gitea/modules/log/log.go:191 +0xcf

goroutine 20 [select]:
code.gitea.io/gitea/modules/log.(*Logger).StartLogger(0xc42046f900)
        /srv/app/src/code.gitea.io/gitea/modules/log/log.go:261 +0x142
created by code.gitea.io/gitea/modules/log.newLogger
        /srv/app/src/code.gitea.io/gitea/modules/log/log.go:191 +0xcf

goroutine 21 [chan receive, 8 minutes]:
code.gitea.io/gitea/modules/mailer.processMailQueue()
        /srv/app/src/code.gitea.io/gitea/modules/mailer/mailer.go:241 +0x71
created by code.gitea.io/gitea/modules/mailer.NewContext
        /srv/app/src/code.gitea.io/gitea/modules/mailer/mailer.go:273 +0xd3

goroutine 22 [chan receive, 8 minutes]:
database/sql.(*DB).connectionOpener(0xc420473400)
        /usr/local/go/src/database/sql/sql.go:837 +0x4a
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:582 +0x212

goroutine 124 [select, 8 minutes]:
code.gitea.io/gitea/vendor/github.com/gogits/cron.(*Cron).run(0xc420452440)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:178 +0x92e
created by code.gitea.io/gitea/vendor/github.com/gogits/cron.(*Cron).Start
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:140 +0x55

goroutine 142 [chan receive, 8 minutes]:
code.gitea.io/gitea/models.processIssueIndexerUpdateQueue()
        /srv/app/src/code.gitea.io/gitea/models/issue_indexer.go:156 +0x60
created by code.gitea.io/gitea/models.InitIssueIndexer
        /srv/app/src/code.gitea.io/gitea/models/issue_indexer.go:92 +0x13a

goroutine 372 [IO wait]:
net.runtime_pollWait(0x7f3103172610, 0x72, 0xc)
        /usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4203d9f08, 0x72, 0x1d65e60, 0x1d5d1a8)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4203d9f08, 0xc4215fd000, 0x1000)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4203d9ea0, 0xc4215fd000, 0x1000, 0x1000, 0x0, 0x1d65e60, 0x1d5d1a8)
        /usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42074f680, 0xc4215fd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc42109a900, 0xc4215fd000, 0x1000, 0x1000, 0x0, 0xc421e55bb0, 0x61d0f8)
        /usr/local/go/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc42089b260)
        /usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc42089b260, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc421e55c10)
        /usr/local/go/src/bufio/bufio.go:129 +0x67
net/http.(*conn).readRequest(0xc421061040, 0x1d6d9a0, 0xc42109a840, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:931 +0xe91
net/http.(*conn).serve(0xc421061040, 0x1d6d9a0, 0xc42109a840)
        /usr/local/go/src/net/http/server.go:1763 +0x49a
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce

goroutine 143 [chan receive, 8 minutes]:
code.gitea.io/gitea/models.SyncMirrors()
        /srv/app/src/code.gitea.io/gitea/models/repo_mirror.go:228 +0x73
created by code.gitea.io/gitea/models.InitSyncMirrors
        /srv/app/src/code.gitea.io/gitea/models/repo_mirror.go:252 +0x35

goroutine 144 [select]:
net/http.(*Transport).getConn(0xc421dcac30, 0xc421ef2440, 0x0, 0xc420ed92c0, 0x4, 0xc421edd780, 0xb, 0x0, 0x0, 0xc421ef2060)
        /usr/local/go/src/net/http/transport.go:913 +0xb92
net/http.(*Transport).RoundTrip(0xc421dcac30, 0xc422008d00, 0xc421dcac30, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:378 +0x58c
net/http.send(0xc422008d00, 0x1d626e0, 0xc421dcac30, 0x0, 0x0, 0x0, 0x0, 0x8, 0xc4218edf60, 0x413298)
        /usr/local/go/src/net/http/client.go:249 +0x162
net/http.(*Client).send(0xc421030570, 0xc422008d00, 0x0, 0x0, 0x0, 0xc4218edf60, 0x0, 0x1, 0x40c53e)
        /usr/local/go/src/net/http/client.go:173 +0x108
net/http.(*Client).Do(0xc421030570, 0xc422008d00, 0xa, 0x13db52e, 0xa)
        /usr/local/go/src/net/http/client.go:595 +0x254
code.gitea.io/gitea/modules/httplib.(*Request).getResponse(0xc421295a40, 0xc42163bb58, 0xc42163bb50, 0xc4205e55c0)
        /srv/app/src/code.gitea.io/gitea/modules/httplib/httplib.go:357 +0x470
code.gitea.io/gitea/modules/httplib.(*Request).Response(0xc421295a40, 0x142da60, 0xc42120ab60, 0x0)
        /srv/app/src/code.gitea.io/gitea/modules/httplib/httplib.go:443 +0x2b
code.gitea.io/gitea/models.(*HookTask).deliver(0xc42120ab60)
        /srv/app/src/code.gitea.io/gitea/models/webhook.go:589 +0x6f1
code.gitea.io/gitea/models.DeliverHooks()
        /srv/app/src/code.gitea.io/gitea/models/webhook.go:643 +0x62f
created by code.gitea.io/gitea/models.InitDeliverHooks
        /srv/app/src/code.gitea.io/gitea/models/webhook.go:654 +0x35

goroutine 145 [chan receive, 8 minutes]:
code.gitea.io/gitea/models.TestPullRequests()
        /srv/app/src/code.gitea.io/gitea/models/pull.go:1086 +0x1c8
created by code.gitea.io/gitea/models.InitTestPullRequests
        /srv/app/src/code.gitea.io/gitea/models/pull.go:1107 +0x35

goroutine 146 [select, 8 minutes]:
code.gitea.io/gitea/modules/log.(*Logger).StartLogger(0xc42046ef50)
        /srv/app/src/code.gitea.io/gitea/modules/log/log.go:261 +0x142
created by code.gitea.io/gitea/modules/log.newLogger
        /srv/app/src/code.gitea.io/gitea/modules/log/log.go:191 +0xcf

goroutine 2685 [runnable]:
database/sql.(*Rows).awaitDone(0xc421ce2080, 0x1d6d9a0, 0xc42120c880)
        /usr/local/go/src/database/sql/sql.go:2120
created by database/sql.(*Rows).initContextClose
        /usr/local/go/src/database/sql/sql.go:2116 +0x92

goroutine 319 [select, 8 minutes, locked to thread]:
runtime.gopark(0x1434d48, 0x0, 0x13d4014, 0x6, 0x18, 0x2)
        /usr/local/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc420581f50, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc420581f50)
        /usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 314 [select]:
code.gitea.io/gitea/vendor/github.com/facebookgo/httpdown.(*server).manage(0xc42141afd0)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/httpdown/httpdown.go:204 +0xa2b
created by code.gitea.io/gitea/vendor/github.com/facebookgo/httpdown.HTTP.Serve
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/httpdown/httpdown.go:96 +0x3df

goroutine 315 [IO wait]:
net.runtime_pollWait(0x7f3103172910, 0x72, 0x1d65e60)
        /usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc421558ae8, 0x72, 0x1d5d1a8, 0xc42186d500)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc421558ae8, 0xffffffffffffffff, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc421558a80, 0x0, 0x1d62ea0, 0xc42186d500)
        /usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42074f400, 0xc420538eb0, 0x71befe, 0x459a40)
        /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc42074f400, 0x14346a8, 0xc420fff7c0, 0x1d6da60, 0xc4216c4420)
        /usr/local/go/src/net/tcpsock.go:228 +0x49
net/http.(*Server).Serve(0xc42141af20, 0x1d6c0a0, 0xc42074f400, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2643 +0x228
code.gitea.io/gitea/vendor/github.com/facebookgo/httpdown.(*server).serve(0xc42141afd0)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/httpdown/httpdown.go:277 +0x83
created by code.gitea.io/gitea/vendor/github.com/facebookgo/httpdown.HTTP.Serve
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/httpdown/httpdown.go:97 +0x401

goroutine 316 [semacquire, 8 minutes]:
sync.runtime_Semacquire(0xc421576b6c)
        /usr/local/go/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc421576b60)
        /usr/local/go/src/sync/waitgroup.go:131 +0x7a
code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp.(*app).wait(0xc421578f60)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp/http.go:85 +0x115
code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp.Serve.func1(0xc4215792c0, 0xc421578f60)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp/http.go:159 +0x51
created by code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp.Serve
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp/http.go:160 +0x3af

goroutine 317 [chan receive, 8 minutes]:
code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp.(*app).signalHandler(0xc421578f60, 0xc421576b60)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp/http.go:103 +0x121
created by code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp.(*app).wait
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp/http.go:76 +0x81

goroutine 318 [chan receive, 8 minutes]:
code.gitea.io/gitea/vendor/github.com/facebookgo/httpdown.(*server).Wait(0xc42141afd0, 0x1434e90, 0xc421576b60)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/httpdown/httpdown.go:283 +0x5b
code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp.(*app).wait.func1(0xc421576b60, 0xc421578f60, 0x1d66de0, 0xc42141afd0)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp/http.go:80 +0x5b
created by code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp.(*app).wait
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/facebookgo/grace/gracehttp/http.go:83 +0xdc

goroutine 2425 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f3103172850, 0x72, 0x8)
        /usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4215d1728, 0x72, 0x1d65e60, 0x1d5d1a8)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4215d1728, 0xc421640000, 0x1000)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4215d16c0, 0xc421640000, 0x1000, 0x1000, 0x0, 0x1d65e60, 0x1d5d1a8)
        /usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4218ec070, 0xc421640000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:181 +0x70
net/http.(*persistConn).Read(0xc421088ea0, 0xc421640000, 0x1000, 0x1000, 0x4, 0x4573a0, 0xc42223e120)
        /usr/local/go/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc421711f80)
        /usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc421711f80, 0x1, 0xc420536be5, 0x1, 0x0, 0xc42223e000, 0x0)
        /usr/local/go/src/bufio/bufio.go:129 +0x67
net/http.(*persistConn).readLoop(0xc421088ea0)
        /usr/local/go/src/net/http/transport.go:1474 +0x196
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1117 +0xa35

goroutine 2426 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc421088ea0)
        /usr/local/go/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1118 +0xa5a

goroutine 2687 [select]:
net.cgoLookupIP(0x1d6da20, 0xc420ea0840, 0xc421edd780, 0x8, 0xc4218edf00, 0x40446e, 0xc4208c8e08, 0xc4208c8e18, 0xc4208c8ea0, 0x418daf)
        /usr/local/go/src/net/cgo_unix.go:214 +0x2f5
net.(*Resolver).lookupIP(0x25493f5, 0x1d6da20, 0xc420ea0840, 0xc421edd780, 0x8, 0xc420661d40, 0xc4208c8e48, 0x4364de, 0xc420661d40, 0xc4208c8e68)
        /usr/local/go/src/net/lookup_unix.go:69 +0x125
net.(*Resolver).(net.lookupIP)-fm(0x1d6da20, 0xc420ea0840, 0xc421edd780, 0x8, 0xc4208c8e98, 0x407824, 0xc4205029c0, 0x4, 0xc4208c8fb0)
        /usr/local/go/src/net/lookup.go:156 +0x56
net.glob..func11(0x1d6da20, 0xc420ea0840, 0xc421edd810, 0xc421edd780, 0x8, 0x0, 0x465518, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/hook.go:19 +0x52
net.(*Resolver).LookupIPAddr.func1(0x4573a0, 0xc420f7ede0, 0xc4218edf00, 0x0)
        /usr/local/go/src/net/lookup.go:162 +0x5c
internal/singleflight.(*Group).doCall(0x2523bd0, 0xc421ef7d60, 0xc421edd780, 0x8, 0xc421030960)
        /usr/local/go/src/internal/singleflight/singleflight.go:93 +0x3c
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:86 +0x323

goroutine 2620 [IO wait]:
net.runtime_pollWait(0x7f3103172250, 0x72, 0xe)
        /usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc422582928, 0x72, 0x1d65e60, 0x1d5d1a8)
        /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc422582928, 0xc420981000, 0x1000)
        /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4225828c0, 0xc420981000, 0x1000, 0x1000, 0x0, 0x1d65e60, 0x1d5d1a8)
        /usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4218ecfb0, 0xc420981000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc420c08640, 0xc420981000, 0x1000, 0x1000, 0x13, 0x0, 0x1d824c0)
        /usr/local/go/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc42223e840)
        /usr/local/go/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc42223e840, 0x45740a, 0x7f31041c2000, 0x2, 0xc420c90a40, 0x412a42, 0x7f31041c2000)
        /usr/local/go/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadLine(0xc42223e840, 0xc42192a200, 0x100, 0xf8, 0x13b3ba0, 0xc42105d760, 0x7f31041c2000)
        /usr/local/go/src/bufio/bufio.go:367 +0x37
net/textproto.(*Reader).readLineSlice(0xc421bd5470, 0xc420c90ac8, 0xc420c90ac8, 0x413298, 0x100, 0x13b3ba0)
        /usr/local/go/src/net/textproto/reader.go:55 +0x5f
net/textproto.(*Reader).ReadLine(0xc421bd5470, 0xc42192a200, 0x72, 0x8000000000000000, 0x0)
        /usr/local/go/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc42223e840, 0x0, 0xc42192a200, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:918 +0xa5
net/http.(*conn).readRequest(0xc420fff7c0, 0x1d6d9a0, 0xc420c08480, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:934 +0x213
net/http.(*conn).serve(0xc420fff7c0, 0x1d6d9a0, 0xc420c08480)
        /usr/local/go/src/net/http/server.go:1763 +0x49a
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce

goroutine 2686 [select]:
net.(*Resolver).LookupIPAddr(0x25493f5, 0x1d6da20, 0xc420ea0840, 0xc421edd780, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/lookup.go:165 +0x9b1
net.(*Resolver).internetAddrList(0x25493f5, 0x1d6da20, 0xc420ea0840, 0x13cf78f, 0x3, 0xc421edd780, 0xb, 0x0, 0x0, 0xc4205376c8, ...)
        /usr/local/go/src/net/ipsock.go:245 +0x4cc
net.(*Resolver).resolveAddrList(0x25493f5, 0x1d6da20, 0xc420ea0840, 0x13d036e, 0x4, 0x13cf78f, 0x3, 0xc421edd780, 0xb, 0x0, ...)
        /usr/local/go/src/net/dial.go:188 +0x6b3
net.(*Dialer).DialContext(0xc421639918, 0x1d6d9e0, 0xc420012390, 0x13cf78f, 0x3, 0xc421edd780, 0xb, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/dial.go:349 +0x247
net.(*Dialer).Dial(0xc420537918, 0x13cf78f, 0x3, 0xc421edd780, 0xb, 0x1, 0x490000004bc974, 0x55, 0x7)
        /usr/local/go/src/net/dial.go:294 +0x75
net.DialTimeout(0x13cf78f, 0x3, 0xc421edd780, 0xb, 0x8bb2c97000, 0x120, 0x110, 0x13b9920, 0x413dcc)
        /usr/local/go/src/net/dial.go:280 +0xa6
code.gitea.io/gitea/modules/httplib.TimeoutDialer.func1(0x13cf78f, 0x3, 0xc421edd780, 0xb, 0xc420537a58, 0x2549918, 0xc420537a60, 0x6b0a6d)
        /srv/app/src/code.gitea.io/gitea/modules/httplib/httplib.go:449 +0x65
net/http.(*Transport).dial(0xc421dcac30, 0x1d6d9e0, 0xc420012390, 0x13cf78f, 0x3, 0xc421edd780, 0xb, 0xc420537b20, 0x894972, 0xc42187bc00, ...)
        /usr/local/go/src/net/http/transport.go:852 +0x7b
net/http.(*Transport).dialConn(0xc421dcac30, 0x1d6d9e0, 0xc420012390, 0x0, 0xc420ed92c0, 0x4, 0xc421edd780, 0xb, 0xc42109ac80, 0x1d62401, ...)
        /usr/local/go/src/net/http/transport.go:1008 +0x1c4c
net/http.(*Transport).getConn.func4(0xc421dcac30, 0x1d6d9e0, 0xc420012390, 0xc4210306c0, 0xc420ed9500)
        /usr/local/go/src/net/http/transport.go:908 +0x78
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:910 +0x3a3
```

## Description
I have no idea why, but my instance of gitea crashs with a SIGSEGV every time when the webhook start. Hook target is my PHP site and second hook is Redmine. I have many repos and every repo have the same webhooks

**Comment by tomas-kulhanek** [comment]
@lunny i think this is same problem like #1408 because when i try what @tboerger says webhooks working fine.

**Comment by tboerger** [comment]
Maybe we should check if we can enforce the go name resolver within our prebuilt binaries.

**Comment by tboerger** [comment]
Looks like we have to build the binary with the build tag `netgo`, because the default `netcgo` seems to fail on some systems. It have been introduced with https://github.com/golang/go/commit/b615ad8fd57f9394db14e403d12061c369379c52

**Comment by tboerger** [comment]
I have created the pull request https://github.com/go-gitea/gitea/pull/1690 which should solve this issue as it enforces the Go name resolution instead of CGO for cross-compiled binaries.

**Comment by tomas-kulhanek** [comment]
After deploy master version ddb63a7 and test of webhook, gitea still working after 2 hours. Thanks for quick fix.
