### ISSUE TITLE
"AssetUrlPrefix" not defined

### ISSUE THREAD

**Issue by SentToDevNull** [go-gitea/gitea#16673]
- Gitea version (or commit ref): latest release
- Operating system: Debian 10 (baremetal)

## Description
When following the official configuration instructions [here](https://docs.gitea.io/en-us/customizing-gitea/#customizing-startpage--homepage) for customizing the start page, Gitea appears to be unable to find its own variables:
```
panic: template: home:6: function "AssetUrlPrefix" not defined
```

Simply follow the official documentation linked above to reproduce this issue.

Here's some output I get when trying to launch Gitea after following the documentation:

```
$ /opt/gitea/gitea --custom-path=/opt/gitea_custom
...
2021/08/12 07:09:31 ...xer/stats/indexer.go:84:populateRepoIndexer() [I] Done (re)populating the repo stats indexer with existing repositories
panic: template: repo/header:39: function "MirrorRemoteAddress" not defined

goroutine 1 [running]:
html/template.Must(...)
        /usr/local/go/src/html/template/template.go:374
github.com/unrolled/render.(*Render).compileTemplatesFromAsset(0xc0021c2480)
        /source/vendor/github.com/unrolled/render/render.go:287 +0x759
github.com/unrolled/render.(*Render).compileTemplates(0xc0021c2480)
        /source/vendor/github.com/unrolled/render/render.go:194 +0x4c
github.com/unrolled/render.New(0xc002a61148, 0x1, 0x1, 0x1)
        /source/vendor/github.com/unrolled/render/render.go:142 +0x133
code.gitea.io/gitea/modules/templates.HTMLRenderer(0xc002a613c0)
        /source/modules/templates/base.go:88 +0x16a
code.gitea.io/gitea/routers/routes.Recovery(0xc0021f8780)
        /source/routers/routes/base.go:147 +0x25
code.gitea.io/gitea/routers/routes.WebRoutes(0xc0021f8680)
        /source/routers/routes/web.go:142 +0x225
code.gitea.io/gitea/routers/routes.NormalRoutes(0xc000359340)
        /source/routers/routes/web.go:120 +0x11b
code.gitea.io/gitea/cmd.runWeb(0xc000359340, 0x0, 0x0)
        /source/cmd/web.go:138 +0x4ae
github.com/urfave/cli.HandleAction(0x2662d20, 0x38ce260, 0xc000359340, 0xc000359340, 0x0)
        /source/vendor/github.com/urfave/cli/app.go:524 +0x105
github.com/urfave/cli.Command.Run(0x2a6dae0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2bd197a, 0x16, 0x0, ...)
        /source/vendor/github.com/urfave/cli/command.go:173 +0x579
github.com/urfave/cli.(*App).Run(0xc00122fc00, 0xc00003c180, 0x3, 0x3, 0x0, 0x0)
        /source/vendor/github.com/urfave/cli/app.go:277 +0x808
main.main()
        /source/main.go:115 +0xa6a
```

**Comment by silverwind** [comment]
Docs link to the 1.15 version of that template but I assume you run 1.14 where the variable was named `StaticUrlPrefix`. Please use the 1.14 template:

https://github.com/go-gitea/gitea/blob/release/v1.14/templates/home.tmpl
