### ISSUE TITLE
Logo generation fails

### ISSUE THREAD

**Issue by tte18** [go-gitea/gitea#17106]
### Gitea Version

1.15.2

### How are you running Gitea?

systemd

### Can you reproduce the bug on the Gitea demo site?

Yes

**Comment by vbakc** [comment]
```shell
$ make generate-images
npm install --no-save

up to date in 1s
npm install --no-save --no-package-lock fabric@4 imagemin-zopfli@7

added 49 packages, removed 74 packages, and changed 153 packages in 1m
node build/generate-images.js 
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /home/hero/openSource/golang/gitea/node_modules/canvas/lib/bindings.js
- /home/hero/openSource/golang/gitea/node_modules/canvas/lib/canvas.js
- /home/hero/openSource/golang/gitea/node_modules/canvas/index.js
- /home/hero/openSource/golang/gitea/node_modules/jsdom/lib/jsdom/utils.js
- /home/hero/openSource/golang/gitea/node_modules/jsdom/lib/jsdom/browser/Window.js
- /home/hero/openSource/golang/gitea/node_modules/jsdom/lib/api.js
- /home/hero/openSource/golang/gitea/node_modules/fabric/dist/fabric.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hero/openSource/golang/gitea/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/hero/openSource/golang/gitea/node_modules/canvas/lib/bindings.js',
    '/home/hero/openSource/golang/gitea/node_modules/canvas/lib/canvas.js',
    '/home/hero/openSource/golang/gitea/node_modules/canvas/index.js',
    '/home/hero/openSource/golang/gitea/node_modules/jsdom/lib/jsdom/utils.js',
    '/home/hero/openSource/golang/gitea/node_modules/jsdom/lib/jsdom/browser/Window.js',
    '/home/hero/openSource/golang/gitea/node_modules/jsdom/lib/api.js',
    '/home/hero/openSource/golang/gitea/node_modules/fabric/dist/fabric.js'
  ]
}
make: *** [Makefile:753: generate-images] Error 1
```

**Comment by vbakc** [comment]
Discussion on forum:
https://discourse.gitea.io/t/logo-generation-fails/3791

**Comment by wxiaoguang** [comment]
Please check if you can get `canvas.node` correctly.

I can do `make generate-images` on the main branch

and `canvas.node` is there:

```
$ file ./node_modules/canvas/build/Release/canvas.node
./node_modules/canvas/build/Release/canvas.node: Mach-O 64-bit bundle x86_64
```
