### ISSUE TITLE
Fixes to #947 broke ssh access to repositories

### ISSUE THREAD

**Issue by trebonian** [go-gitea/gitea#1771]
- Gitea version (or commit ref): cf02cd7ba0c94165743660cf30f0cbb5a73a385e
- Git version: 2.13.0
- Operating system: Alpine Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x ] Not relevant
- Log gist: https://gist.github.com/trebonian/d9cbb2971eef6e4502e8e28fdb8bb4ca

## Description
Any access to repository via git causes a crash. It appears that my repository wasn't migrated to include #947 team-units and the latest set of fixes try and access the units.
What procedure do I need to execute to update the repositories? Or can the code be more properly backwards compatible with the old repository version.

## Screenshots

**If this issue involves the Web Interface, please include a screenshot**

**Comment by trebonian** [comment]
This appears to be the same as issue #1768 - sorry for duplicate.

alpine:~/gitea$ git remote show barry
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x202f28bec0e]

goroutine 1 [running]:
panic(0x202f4215580, 0xc420010080)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a5
code.gitea.io/gitea/models.(*Repository).getUnitsByUserID(0xc4201a9340, 0x202f4b8bc80, 0xc420292280, 0x1, 0x1, 0x0, 0x0)
        /srv/app/src/code.gitea.io/gitea/models/repo.go:361 +0x8e
code.gitea.io/gitea/models.(*Repository).CheckUnitUser(0xc4201a9340, 0x1, 0x1, 0x1, 0x0)
        /srv/app/src/code.gitea.io/gitea/models/repo.go:334 +0x5c
code.gitea.io/gitea/cmd.runServ(0xc4200bf400, 0x0, 0xc4200bf400)
        /srv/app/src/code.gitea.io/gitea/cmd/serv.go:253 +0x1e6d
code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0x202f41cab00, 0x202f43b2a48, 0xc4200bf400, 0xc420053b00, 0x0)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xbb
code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x202f38653bf, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x202f38bd9bf, 0x2f, 0x0, ...)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0xcc9
code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc4203a2d00, 0xc42000c1c0, 0x4, 0x4, 0x0, 0x0)
        /srv/app/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x6a5
main.main()
        /srv/app/src/code.gitea.io/gitea/main.go:44 +0x3ac
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
