### ISSUE TITLE
Make doesn't work anymore

### ISSUE THREAD

**Issue by marcelloh** [go-gitea/gitea#21860]
### Description

running make gives an error:

mh@disk Gitea % make
rm -rf public/js public/css public/fonts public/img/webpack public/serviceworker.js
npx webpack
[webpack-cli] HookWebpackError: The service is no longer running
    at makeWebpackError (/Users/mh/data/Go/go-tools/Gitea/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/mh/data/Go/go-tools/Gitea/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/Users/mh/data/Go/go-tools/Gitea/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:43:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
-- inner error --
Error: The service is no longer running
    at /Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:1400:29
    at sendRequest (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:674:14)
    at start (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:1398:9)
    at Object.transform2 [as transform] (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:1455:5)
    at /Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:2135:55
    at new Promise (<anonymous>)
    at Object.transform (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:2135:14)
    at ESBuildMinifyPlugin.transform (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:1958:62)
    at /Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild-loader/dist/minify-plugin.js:75:39
    at Array.map (<anonymous>)
    at ESBuildMinifyPlugin.transformAssets (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild-loader/dist/minify-plugin.js:71:34)
    at /Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild-loader/dist/minify-plugin.js:41:43
    at fn (/Users/mh/data/Go/go-tools/Gitea/node_modules/webpack/lib/Compilation.js:536:19)
    at Hook.eval [as callAsync] (eval at create (/Users/mh/data/Go/go-tools/Gitea/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:35:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mh/data/Go/go-tools/Gitea/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/Users/mh/data/Go/go-tools/Gitea/node_modules/webpack/lib/Compilation.js:3057:34)
caused by plugins in Compilation.hooks.processAssets
Error: The service is no longer running
    at /Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:1400:29
    at sendRequest (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:674:14)
    at start (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:1398:9)
    at Object.transform2 [as transform] (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:1455:5)
    at /Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:2135:55
    at new Promise (<anonymous>)
    at Object.transform (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:2135:14)
    at ESBuildMinifyPlugin.transform (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild/lib/main.js:1958:62)
    at /Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild-loader/dist/minify-plugin.js:75:39
    at Array.map (<anonymous>)
    at ESBuildMinifyPlugin.transformAssets (/Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild-loader/dist/minify-plugin.js:71:34)
    at /Users/mh/data/Go/go-tools/Gitea/node_modules/esbuild-loader/dist/minify-plugin.js:41:43
    at fn (/Users/mh/data/Go/go-tools/Gitea/node_modules/webpack/lib/Compilation.js:536:19)
    at Hook.eval [as callAsync] (eval at create (/Users/mh/data/Go/go-tools/Gitea/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:35:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mh/data/Go/go-tools/Gitea/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/Users/mh/data/Go/go-tools/Gitea/node_modules/webpack/lib/Compilation.js:3057:34)
make: *** [public/js/index.js] Error 2

### Gitea Version

latest (git pulled just now)

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

git version 2.37.3

### How are you running Gitea?

download and run, but this is about updating (pull) and build (with make)

**Comment by silverwind** [comment]
How much memory does your machine have?

According to https://github.com/evanw/esbuild/issues/1506#issuecomment-894668760 it might be because esbuild runs out of memory.

**Comment by silverwind** [comment]
Also check if this works:

```
NODE_OPTIONS="--max-old-space-size=4096" TAGS="bindata" make build

**Comment by marcelloh** [comment]
last one gives me the same error. (macBook has 16Gb)

**Comment by silverwind** [comment]
Ok, then I'm out of ideas. Something seems to be killing your esbuild process. Maybe some overzeaulous security software?

**Comment by marcelloh** [comment]
I've disabled Bitdefender, but same result. I must say "The service is no longer running" is pretty vague.
So if you know what service it could be, I might be able to look into that. Is it a service that the build depends upon? Is it a service that is/should be available in my OS?

**Comment by silverwind** [comment]
Don't know, but i assume "service" refers to the esbuild process that is started during the webpack build, but all I can do is google the error message. Maybe check the OS log files (Utilities -> Console) if there is anything suspicious when you run it.

**Comment by marcelloh** [comment]
```
2022-11-19 12:07:14.366743 (system/com.apple.ManagedClient) <Notice>: internal event: WILL_SPAWN, code = 0
2022-11-19 12:07:14.366801 (system/com.apple.ManagedClient) <Notice>: service state: spawn scheduled
2022-11-19 12:07:14.366805 (system/com.apple.ManagedClient) <Notice>: service state: spawning
2022-11-19 12:07:14.366830 (system/com.apple.ManagedClient) <Notice>: launching: ipc (mach)
2022-11-19 12:07:14.367818 (system/com.apple.ManagedClient [2729]) <Notice>: xpcproxy spawned with pid 2729
2022-11-19 12:07:14.367839 (system/com.apple.ManagedClient [2729]) <Notice>: internal event: SPAWNED, code = 0
2022-11-19 12:07:14.367843 (system/com.apple.ManagedClient [2729]) <Notice>: service state: xpcproxy
2022-11-19 12:07:14.367853 (system/com.apple.ManagedClient [2729]) <Notice>: internal event: SOURCE_ATTACH, code = 0
2022-11-19 12:07:14.376213 (system/com.apple.ManagedClient [2729]) <Notice>: service state: running
2022-11-19 12:07:14.376233 (system/com.apple.ManagedClient [2729]) <Notice>: internal event: INIT, code = 0
2022-11-19 12:07:14.376241 (system/com.apple.ManagedClient [2729]) <Notice>: Successfully spawned ManagedClient[2729] because ipc (mach)
2022-11-19 12:07:14.393127 (pid/2729 [ManagedClient]) <Notice>: uncorking exec source upfront
2022-11-19 12:07:14.393157 (pid/2729 [ManagedClient]) <Notice>: created
2022-11-19 12:07:14.483961 (system/com.apple.mdmclient.daemon) <Notice>: internal event: WILL_SPAWN, code = 0
2022-11-19 12:07:14.483994 (system/com.apple.mdmclient.daemon) <Notice>: service state: spawn scheduled
2022-11-19 12:07:14.483996 (system/com.apple.mdmclient.daemon) <Notice>: service state: spawning
2022-11-19 12:07:14.484017 (system/com.apple.mdmclient.daemon) <Notice>: launching: ipc (mach)
2022-11-19 12:07:14.485104 (system/com.apple.mdmclient.daemon [2730]) <Notice>: xpcproxy spawned with pid 2730
2022-11-19 12:07:14.485126 (system/com.apple.mdmclient.daemon [2730]) <Notice>: internal event: SPAWNED, code = 0
2022-11-19 12:07:14.485129 (system/com.apple.mdmclient.daemon [2730]) <Notice>: service state: xpcproxy
2022-11-19 12:07:14.485159 (system/com.apple.mdmclient.daemon [2730]) <Notice>: internal event: SOURCE_ATTACH, code = 0
2022-11-19 12:07:14.494039 (system/com.apple.mdmclient.daemon [2730]) <Notice>: service state: running
2022-11-19 12:07:14.494066 (system/com.apple.mdmclient.daemon [2730]) <Notice>: internal event: INIT, code = 0
2022-11-19 12:07:14.494073 (system/com.apple.mdmclient.daemon [2730]) <Notice>: job state = running
2022-11-19 12:07:14.494084 (system/com.apple.mdmclient.daemon [2730]) <Notice>: Successfully spawned mdmclient[2730] because ipc (mach)
2022-11-19 12:07:14.507999 (pid/2730 [mdmclient]) <Notice>: uncorking exec source upfront
2022-11-19 12:07:14.508035 (pid/2730 [mdmclient]) <Notice>: created
2022-11-19 12:07:14.557244 (pid/2730 [mdmclient]) <Notice>: uncorking domain
2022-11-19 12:07:14.560599 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.AppStoreDaemon.StoreAEService
2022-11-19 12:07:14.560625 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.AppStoreDaemon.StoreUIService
2022-11-19 12:07:14.560629 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.AssetCacheProfilePlugin
2022-11-19 12:07:14.560633 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.BTMProfileService
2022-11-19 12:07:14.560638 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.CGXPCServicesAgent
2022-11-19 12:07:14.560642 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.CMValidateMovieDataReferenceService
2022-11-19 12:07:14.560644 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.ClassroomKit.ClassroomMCXService
2022-11-19 12:07:14.560651 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.ColorSyncXPCAgent
2022-11-19 12:07:14.560654 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.CoreDisplay.XPCService
2022-11-19 12:07:14.560672 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.ExecutionPolicyService
2022-11-19 12:07:14.560674 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.FeatureFlagsProfileService
2022-11-19 12:07:14.560677 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.HasTRB
2022-11-19 12:07:14.560680 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.ImageIOXPCService
2022-11-19 12:07:14.560683 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.LOMXPCService
2022-11-19 12:07:14.560687 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.LocalAuthenticationRemoteService
2022-11-19 12:07:14.560689 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.LoginUserService
2022-11-19 12:07:14.560796 (pid/2730/com.apple.MTLCompilerService) <Notice>: created the implicit endpoint upfront
2022-11-19 12:07:14.560806 (pid/2730/com.apple.MTLCompilerService) <Notice>: draining messages from com.apple.MTLCompilerService
2022-11-19 12:07:14.560835 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.PerfPowerTelemetryClientRegistrationService
2022-11-19 12:07:14.560839 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.RemoteManagementMCXService
2022-11-19 12:07:14.560846 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.StreamingUnzipService
2022-11-19 12:07:14.560849 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.SystemExtensionsMDM
2022-11-19 12:07:14.560853 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.TCCProfileService
2022-11-19 12:07:14.560870 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.appkit.xpc.ColorPickerImageLoader
2022-11-19 12:07:14.560878 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.appkit.xpc.LegacyExternalColorPickerService.arm64
2022-11-19 12:07:14.560881 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.appkit.xpc.LegacyExternalColorPickerService.x86_64
2022-11-19 12:07:14.560886 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.appkit.xpc.VersionsUIHelper
2022-11-19 12:07:14.560893 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.appkit.xpc.WindowSharingControlViewService
2022-11-19 12:07:14.560895 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.appkit.xpc.defaultSyncService
2022-11-19 12:07:14.560898 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.appkit.xpc.documentPopoverViewService
2022-11-19 12:07:14.560901 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.appkit.xpc.openAndSavePanelService
2022-11-19 12:07:14.560903 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.appkit.xpc.sandboxedServiceRunner
2022-11-19 12:07:14.560946 (pid/2730/com.apple.audio.AUHostingService.arm64e) <Notice>: created the implicit endpoint upfront
2022-11-19 12:07:14.564651 <Notice>: Flushed 29 logs [limit: 20]
2022-11-19 12:07:14.560956 (pid/2730/com.apple.audio.AUHostingService.arm64e) <Notice>: draining messages from com.apple.audio.AUHostingService.arm64e
2022-11-19 12:07:14.560992 (pid/2730/com.apple.audio.AUHostingService.x86-64) <Notice>: created the implicit endpoint upfront
2022-11-19 12:07:14.560994 (pid/2730/com.apple.audio.AUHostingService.x86-64) <Notice>: draining messages from com.apple.audio.AUHostingService.x86-64
2022-11-19 12:07:14.560998 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.audio.CarbonComponentScanner.x86-64
2022-11-19 12:07:14.561001 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.audio.ComponentTagHelper
2022-11-19 12:07:14.561030 (pid/2730/com.apple.audio.Core-Audio-Driver-Service) <Notice>: created the implicit endpoint upfront
2022-11-19 12:07:14.561035 (pid/2730/com.apple.audio.Core-Audio-Driver-Service) <Notice>: draining messages from com.apple.audio.Core-Audio-Driver-Service
2022-11-19 12:07:14.561067 (pid/2730/com.apple.audio.Core-Audio-Driver-Service.helper) <Notice>: created the implicit endpoint upfront
2022-11-19 12:07:14.561074 (pid/2730/com.apple.audio.Core-Audio-Driver-Service.helper) <Notice>: draining messages from com.apple.audio.Core-Audio-Driver-Service.helper
2022-11-19 12:07:14.561080 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.audio.DriverHelper
2022-11-19 12:07:14.561083 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.audio.InfoHelper
2022-11-19 12:07:14.561086 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.audio.SandboxHelper
2022-11-19 12:07:14.561099 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.automator.xpc.workflowServiceRunner
2022-11-19 12:07:14.561109 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.coremedia.pluginformatreader
2022-11-19 12:07:14.561112 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.coremedia.pluginformatreader.zonto
2022-11-19 12:07:14.561116 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.coremedia.videodecoder
2022-11-19 12:07:14.561118 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.coremedia.videodecoder.zonto
2022-11-19 12:07:14.561121 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.coremedia.videoencoder
2022-11-19 12:07:14.561123 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.coremedia.videoencoder.zonto
2022-11-19 12:07:14.561126 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.desktopservices.ArchiveService
2022-11-19 12:07:14.561131 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.diskimagescontroller
2022-11-19 12:07:14.561135 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.extensionkitservice
2022-11-19 12:07:14.561139 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.foundation.UserScriptService
2022-11-19 12:07:14.561153 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.icloud.FindMyDevice.FindMyDeviceEraseXPCService
2022-11-19 12:07:14.561156 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.icloud.FindMyDevice.FindMyDeviceIdentityXPCService
2022-11-19 12:07:14.561161 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.intents.intents-helper
2022-11-19 12:07:14.561163 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.internal.DataDetectorsRemoteScanner
2022-11-19 12:07:14.561178 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.AirPlay
2022-11-19 12:07:14.561190 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.AppleService
2022-11-19 12:07:14.561192 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.Assessment
2022-11-19 12:07:14.561196 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.CardDAV
2022-11-19 12:07:14.561200 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.Certificate
2022-11-19 12:07:14.561202 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.EraseDevice
2022-11-19 12:07:14.561206 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.Exchange
2022-11-19 12:07:14.561209 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.FileVaultEscrow
2022-11-19 12:07:14.561212 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.Firewall
2022-11-19 12:07:14.561215 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.FirmwarePassword
2022-11-19 12:07:14.561219 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.Font
2022-11-19 12:07:14.561223 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.MAIDService
2022-11-19 12:07:14.561226 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.MDM
2022-11-19 12:07:14.561229 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.PlugInKit
2022-11-19 12:07:14.561232 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.SampleService
2022-11-19 12:07:14.561235 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.SingleSignOn
2022-11-19 12:07:14.561240 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.managedclient.pds.SystemPolicy
2022-11-19 12:07:14.561256 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.security.XPCAcmeService
2022-11-19 12:07:14.561267 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.security.pboxd
2022-11-19 12:07:14.561271 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.speech.SpeechSynthesisServerXPC
2022-11-19 12:07:14.561281 (pid/2730 [mdmclient]) <Notice>: Service stub created for com.apple.textkit.nsattributedstringagent
2022-11-19 12:07:14.566123 <Notice>: Flushed 48 logs [limit: 20]
2022-11-19 12:07:14.611095 (system) <Notice>: Enabling service com.apple.mdmclient.daemon.runatboot
2022-11-19 12:07:19.359640 <Notice>: Last log repeated 1 times
2022-11-19 12:07:19.359539 (system) <Warning>: failed lookup: name = com.apple.AppleLOM.Watchdog, flags = 0x1, requestor = watchdogd[348], error = 3: No such process
2022-11-19 12:07:23.124274 (pid/2156 [Console]) <Notice>: Service stub created for com.apple.ctcategories.service
2022-11-19 12:07:34.553996 (system/com.apple.ManagedClient [2729]) <Notice>: exited due to exit(0)
2022-11-19 12:07:34.554047 (system/com.apple.ManagedClient [2729]) <Notice>: service state: exited
2022-11-19 12:07:34.554058 (system/com.apple.ManagedClient [2729]) <Notice>: internal event: EXITED, code = 0
2022-11-19 12:07:34.554065 (system) <Notice>: service inactive: com.apple.ManagedClient
2022-11-19 12:07:34.554091 (system/com.apple.ManagedClient [2729]) <Notice>: service state: not running
2022-11-19 12:07:34.554107 (pid/2729 [ManagedClient]) <Notice>: shutting down
2022-11-19 12:07:34.554121 (pid/2729 [ManagedClient]) <Notice>: cleaning up
2022-11-19 12:07:34.554134 (system) <Notice>: removing child: pid/2729
2022-11-19 12:07:36.575727 (system/com.apple.mdmclient.daemon [2730]) <Notice>: exited due to exit(0)
2022-11-19 12:07:36.575756 (system/com.apple.mdmclient.daemon [2730]) <Notice>: service state: exited
2022-11-19 12:07:36.575764 (system/com.apple.mdmclient.daemon [2730]) <Notice>: internal event: EXITED, code = 0
2022-11-19 12:07:36.575769 (system/com.apple.mdmclient.daemon [2730]) <Notice>: job state = exited
2022-11-19 12:07:36.575818 (system) <Notice>: service inactive: com.apple.mdmclient.daemon
2022-11-19 12:07:36.575909 (system/com.apple.mdmclient.daemon [2730]) <Notice>: service state: not running
2022-11-19 12:07:36.575922 (pid/2730 [mdmclient]) <Notice>: shutting down
2022-11-19 12:07:36.575937 (pid/2730/com.apple.MTLCompilerService) <Notice>: internal event: PETRIFIED, code = 0
2022-11-19 12:07:36.575956 (pid/2730/com.apple.audio.AUHostingService.x86-64) <Notice>: internal event: PETRIFIED, code = 0
2022-11-19 12:07:36.575967 (pid/2730/com.apple.audio.AUHostingService.arm64e) <Notice>: internal event: PETRIFIED, code = 0
2022-11-19 12:07:36.575977 (pid/2730/com.apple.audio.Core-Audio-Driver-Service.helper) <Notice>: internal event: PETRIFIED, code = 0
2022-11-19 12:07:36.576101 (pid/2730/com.apple.audio.Core-Audio-Driver-Service) <Notice>: internal event: PETRIFIED, code = 0
2022-11-19 12:07:36.576223 (pid/2730 [mdmclient]) <Notice>: cleaning up
2022-11-19 12:07:36.576231 (system) <Notice>: removing child: pid/2730

```

**Comment by silverwind** [comment]
Don't see anything unusual there. Maybe esbuild is crashing on its own.

**Comment by marcelloh** [comment]
that works, I see nothing of a crash

**Comment by marcelloh** [comment]
I just saw the comment `rm -rf node_modules` which worked. Thanks.
