### ISSUE TITLE
release-latest failure, possibly xgo-related

### ISSUE THREAD

**Issue by silverwind** [go-gitea/gitea#21898]
On `main` branch `release-latest` seems to be failing consistenly since a few commits ago. I think it's caused by or related to xgo. First build that failed was https://drone.gitea.io/go-gitea/gitea/63566/4/5.

The `xgo@latest` dependency is not locked to a specific version, so it's a moving target. I guess we need to lock it down and only manually update it to prevent such failures in the future.

```
Cross compiling ....

Building locally ....

Compiling for windows-4.0/amd64...

panic: path "--ldflags= -linkmode external -extldflags \"-static\"  -X \"main.MakeVersion=GNU Make 4.1\" -X \"main.Version=1.19.0+dev-106-g371dd96e3\" -X \"main.Tags=bindata sqlite sqlite_unlock_notify\"" not in error "invalid import path \"--ldflags= -linkmode external -extldflags \\\"-static\\\"  -X \\\"main.MakeVersion=GNU Make 4.1\\\" -X \\\"main.Version=1.19.0+dev-106-g371dd96e3\\\" -X \\\"main.Tags=bindata sqlite sqlite_unlock_notify\\\"\"" [recovered]

	panic: path "--ldflags= -linkmode external -extldflags \"-static\"  -X \"main.MakeVersion=GNU Make 4.1\" -X \"main.Version=1.19.0+dev-106-g371dd96e3\" -X \"main.Tags=bindata sqlite sqlite_unlock_notify\"" not in error "invalid import path \"--ldflags= -linkmode external -extldflags \\\"-static\\\"  -X \\\"main.MakeVersion=GNU Make 4.1\\\" -X \\\"main.Version=1.19.0+dev-106-g371dd96e3\\\" -X \\\"main.Tags=bindata sqlite sqlite_unlock_notify\\\"\""


goroutine 1 [running]:

cmd/go/internal/load.(*preload).flush(0xc000a34390)

	/usr/local/go/src/cmd/go/internal/load/pkg.go:1086 +0x78

panic({0x97d420, 0xc001ebe310})

	/usr/local/go/src/runtime/panic.go:884 +0x212

cmd/go/internal/load.ImportErrorf({0x7ffc7cfead8b, 0xb6}, {0xa2f3a2?, 0xb6?}, {0xc0002fd630?, 0xc0002fdb18?, 0x0?})

	/usr/local/go/src/cmd/go/internal/load/pkg.go:523 +0x199

cmd/go/internal/load.(*Package).load(0xc002156b00, {0xb2e690, 0xc00002e178}, {0x0, 0x0, 0x0, 0x1, 0x0, 0x0}, {0x7ffc7cfead8b, ...}, ...)

	/usr/local/go/src/cmd/go/internal/load/pkg.go:1894 +0x147d

cmd/go/internal/load.loadImport({0xb2e690, 0xc00002e178}, {0x0, 0x0, 0x0, 0x1, 0x0, 0x0}, 0xc000a34390, {0x7ffc7cfead8b, ...}, ...)

	/usr/local/go/src/cmd/go/internal/load/pkg.go:744 +0x570

cmd/go/internal/load.PackagesAndErrors({0xb2e690?, 0xc00002e178?}, {0x0, 0x0, 0x0, 0x1, 0x0, 0x0}, {0xc0000240d0, 0x9, ...})

	/usr/local/go/src/cmd/go/internal/load/pkg.go:2794 +0x87b

cmd/go/internal/work.runBuild({0xb2e690, 0xc00002e178}, 0xc0000307c8?, {0xc0000240d0, 0x9, 0x9})

	/usr/local/go/src/cmd/go/internal/work/build.go:408 +0xba

main.invoke(0xe298a0, {0xc0000240c0, 0xa, 0xa})

	/usr/local/go/src/cmd/go/main.go:225 +0x34e

main.main()

	/usr/local/go/src/cmd/go/main.go:179 +0x7d1

2022/11/22 03:36:50 Failed to cross compile package: exit status 2.

exit status 1

Makefile:761: recipe for target 'release-windows' failed
```

**Comment by silverwind** [comment]
The `xgo` dependency is not locked to a specific version, so it's a moving target. I guess we should ideally lock it down and only manually update it to prevent such failures in the future.

**Comment by silverwind** [comment]
@techknowlogick what do you think about locking down the xgo version?

**Comment by silverwind** [comment]
Looks https://github.com/techknowlogick/xgo/pull/184 will fix it.

**Comment by zeripath** [comment]
yeah sorry mea culpa.

**Comment by zeripath** [comment]
should be fixed now

**Comment by silverwind** [comment]
Still I wonder whether we should just pin xgo to version, e.g. that's `v1.5.0+1.19` currently.

**Comment by zeripath** [comment]
No then every time there's a go 1.19 minor update we'll have to push another PR
