### ISSUE TITLE
Bug when start in language stats checking

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#21905]
```
panic: runtime error: slice bounds out of range [:-1]

goroutine 1699 [running]:
code.gitea.io/gitea/modules/git.newSignatureFromCommitline({0xc001ae3e87, 0x2c, 0x2d})
	/go/src/code.gitea.io/gitea/modules/git/signature_nogogit.go:54 +0x75d
code.gitea.io/gitea/modules/git.(*Signature).Decode(...)
	/go/src/code.gitea.io/gitea/modules/git/signature_nogogit.go:33
code.gitea.io/gitea/modules/git.CommitFromReader(0xc006772580, {0xea, 0x18, 0x79, 0x14, 0x37, 0x9a, 0x31, 0x37, 0xa4, ...}, ...)
	/go/src/code.gitea.io/gitea/modules/git/commit_reader.go:82 +0x9bd
code.gitea.io/gitea/modules/git.(*Repository).GetLanguageStats(0xc006772580, {0xc001b51470, 0x28})
	/go/src/code.gitea.io/gitea/modules/git/repo_language_stats_nogogit.go:49 +0x4d0
code.gitea.io/gitea/modules/indexer/stats.(*DBIndexer).Index(0x0?, 0xc0066dddf8?)
	/go/src/code.gitea.io/gitea/modules/indexer/stats/db.go:64 +0x60b
code.gitea.io/gitea/modules/indexer/stats.handle({0xc0066d9580?, 0x1, 0x6b000000006fac00?})
	/go/src/code.gitea.io/gitea/modules/indexer/stats/queue.go:23 +0x8f
code.gitea.io/gitea/modules/queue.NewPersistableChannelUniqueQueue.func1({0xc0066d9580?, 0xc0066ddffa?, 0xc001aa3d40?})
	/go/src/code.gitea.io/gitea/modules/queue/unique_queue_disk_channel.go:60 +0x42
code.gitea.io/gitea/modules/queue.NewChannelUniqueQueue.func1({0xc001ae52c0?, 0x14, 0x2b8d244?})
	/go/src/code.gitea.io/gitea/modules/queue/unique_queue_channel.go:80 +0x1ea
code.gitea.io/gitea/modules/queue.(*WorkerPool).doWork(0xc001a51d40, {0x40a30c8, 0xc006693c80})
	/go/src/code.gitea.io/gitea/modules/queue/workerpool.go:552 +0x85f
code.gitea.io/gitea/modules/queue.(*WorkerPool).addWorkers.func1()
	/go/src/code.gitea.io/gitea/modules/queue/workerpool.go:312 +0x65
created by code.gitea.io/gitea/modules/queue.(*WorkerPool).addWorkers
	/go/src/code.gitea.io/gitea/modules/queue/workerpool.go:310 +0x3f
```

**Comment by lunny** [comment]
duplicated with #21900
