### ISSUE TITLE
Javascript error when editing issue description / reply.

### ISSUE THREAD

**Issue by rubenelshof** [go-gitea/gitea#23247]
### Description

When editing the description or reply of a issue I get the following Javascript error:

`
JavaScript error: Uncaught TypeError: i.onChange is not a function (https://git.dionysussg.xyz/assets/js/index.js?v=1.20.0~dev-56-gde6c718b4 @ 60:408). Open browser console to see more details.
`

Console error:
```
Uncaught (in promise) TypeError: i.onChange is not a function
    at index.js?v=1.20.0~dev-56-gde6c718b4:60:408
    at easymde.9b7a25f9.js:13:3720
    at Bl (easymde.9b7a25f9.js:13:3200)
    at Ml (easymde.9b7a25f9.js:13:3477)
    at Lr (easymde.9b7a25f9.js:18:7672)
    at Bt.setValue (easymde.9b7a25f9.js:18:10623)
    at H.value (easymde.9b7a25f9.js:49:18586)
    at HTMLAnchorElement.<anonymous> (index.js?v=1.20.0~dev-56-gde6c718b4:96:3618)
    at Generator.next (<anonymous>)
    at _ (index.js?v=1.20.0~dev-56-gde6c718b4:91:7717)

Uncaught TypeError: i.onChange is not a function
    at index.js?v=1.20.0~dev-56-gde6c718b4:60:408
    at easymde.9b7a25f9.js:13:3720
    at Bl (easymde.9b7a25f9.js:13:3200)
    at Ml (easymde.9b7a25f9.js:13:3477)
    at Lr (easymde.9b7a25f9.js:18:7672)
    at HTMLDivElement.<anonymous> (easymde.9b7a25f9.js:18:10332)
```

### Screenshots

![image](https://user-images.githubusercontent.com/15641671/222453747-1193bf99-04b4-4d85-8d03-0a0bd9e06087.png)

### Gitea Version

1.20.0+dev-56-gde6c718b4

### Can you reproduce the bug on the Gitea demo site?

No

### Browser Version

Chrome 110.0.5481.178

**Comment by delvh** [comment]
I think there is already a PR open to fix it/merged already, I just don't know which one it is.
@wxiaoguang do you know which one it is?

**Comment by wxiaoguang** [comment]
This one: https://github.com/go-gitea/gitea/pull/23168

The one-line fix:  `easyMDEOptions?.onChange?.(...args);`: https://github.com/go-gitea/gitea/pull/23168/files#diff-5eca01f7999043471c646505421dd1362dc17aeba4f600b72ac1c1e76864d7e1R81
