### ISSUE TITLE
Intermittent CI Failure TestPersistableChannelUniqueQueue

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#23977]
### Description

```log
ok  	code.gitea.io/gitea/modules/public	0.100s	coverage: 7.7% of statements

2023/04/07 10:45:59 ...ueue_channel_test.go:169:func3() [I] Finally terminating

2023/04/07 10:45:59 ...eue/queue_channel.go:129:func1() [W] ChannelQueue: test-queue-channel Terminated before completed flushing

2023/04/07 10:46:00 ...disk_channel_test.go:202:func1() [I] [642ff468-2] pausing

2023/04/07 10:46:01 ...disk_channel_test.go:202:func1() [I] [642ff468-4] pausing

2023/04/07 10:46:01 ...disk_channel_test.go:257:func3() [I] Finally terminating

TempDir /tmp/TestPersistableChannelUniqueQueue1161295328/001

2023/04/07 10:46:03 ...ueue_disk_channel.go:314:Shutdown() [W] [642ff46a-7] PersistableChannelUniqueQueue: QueueB 79 will be restored on restart

panic: send on closed channel


goroutine 361 [running]:

code.gitea.io/gitea/modules/queue.(*WorkerPool).pushBoost(0xc0008c0750, {0x103fd60, 0xc00023dbe0})

	/drone/src/modules/queue/workerpool.go:153 +0xb6

code.gitea.io/gitea/modules/queue.(*WorkerPool).Push(0xc0008c0750, {0x103fd60, 0xc00023dbe0})

	/drone/src/modules/queue/workerpool.go:108 +0x1f9

code.gitea.io/gitea/modules/queue.(*ChannelUniqueQueue).PushFunc(0xc000329340, {0x103fd60, 0xc00023dbe0}, 0x0)

	/drone/src/modules/queue/unique_queue_channel.go:143 +0x2bd

code.gitea.io/gitea/modules/queue.(*PersistableChannelUniqueQueue).PushFunc(0xc0003292d0, {0x103fd60, 0xc00023dbe0}, 0x48a05b?)

	/drone/src/modules/queue/unique_queue_disk_channel.go:153 +0x130

code.gitea.io/gitea/modules/queue.(*PersistableChannelUniqueQueue).Push(0xc002205baf?, {0x103fd60, 0xc00023dbe0})

	/drone/src/modules/queue/unique_queue_disk_channel.go:144 +0x54

code.gitea.io/gitea/modules/queue.NewPersistableChannelUniqueQueue.func2({0xc000272e50, 0x1, 0x10?})

	/drone/src/modules/queue/unique_queue_disk_channel.go:105 +0xf9

code.gitea.io/gitea/modules/queue.NewByteFIFOUniqueQueue.func1({0xc000272e50, 0x1, 0x1})

	/drone/src/modules/queue/queue_bytefifo.go:398 +0x93

code.gitea.io/gitea/modules/queue.(*WorkerPool).FlushWithContext(0xc0002b0f30, {0x25137c8, 0xc000276140})

	/drone/src/modules/queue/workerpool.go:503 +0x4c9

code.gitea.io/gitea/modules/queue.(*WorkerPool).Flush(0x4889ac?, 0x48a05b?)

	/drone/src/modules/queue/workerpool.go:458 +0xaf

code.gitea.io/gitea/modules/queue.(*ByteFIFOQueue).Flush(0xc0002be000, 0x396c120?)

	/drone/src/modules/queue/queue_bytefifo.go:150 +0xc5

code.gitea.io/gitea/modules/queue.(*PersistableChannelUniqueQueue).Run.func4()

	/drone/src/modules/queue/unique_queue_disk_channel.go:219 +0xdf

created by code.gitea.io/gitea/modules/queue.(*PersistableChannelUniqueQueue).Run

	/drone/src/modules/queue/unique_queue_disk_channel.go:216 +0x6f2

FAIL	code.gitea.io/gitea/modules/queue	3.668s
```

### Gitea Version

main

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

run the CI

### Database

None

**Comment by silverwind** [comment]
Long-standing issue. Should fix or disable.

**Comment by wxiaoguang** [comment]
And this one? 
* #23608
