### ISSUE TITLE
make watch error displayed in console.

### ISSUE THREAD

**Issue by lunny** [go-gitea/gitea#25228]
```log
95% emitting emit/Users/lunny/data/Projects/gitea/gitea/node_modules/webpack/lib/Compiler.js:769
								cacheEntry.sizeOnlySource = new SizeOnlySource(size);
								                            ^

TypeError: SizeOnlySource is not a constructor
    at updateFileWithReplacementSource (/Users/lunny/data/Projects/gitea/gitea/node_modules/webpack/lib/Compiler.js:769:37)
    at updateWithReplacementSource (/Users/lunny/data/Projects/gitea/gitea/node_modules/webpack/lib/Compiler.js:751:8)
    at processMissingFile (/Users/lunny/data/Projects/gitea/gitea/node_modules/webpack/lib/Compiler.js:814:8)
    at /Users/lunny/data/Projects/gitea/gitea/node_modules/webpack/lib/Compiler.js:856:10
    at callback (/Users/lunny/data/Projects/gitea/gitea/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:211:21)

Node.js v18.4.0
make[1]: *** [watch-frontend] Error 1
```

**Comment by wxiaoguang** [comment]
`rm -rf node_modules`
