### ISSUE TITLE
SSH transport fail on latest master

### ISSUE THREAD

**Issue by pztrn** [go-gitea/gitea#2885]
- Gitea version (or commit ref): 524cca3
- Git version: 2.11.0
- Operating system: Debian 9
- Database (use `[x]`):
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Gitea crashes when trying to push with SSH transport:

```
2017/11/11 09:25:43 Serving [::]:3000 with pid 14763
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc8b181]

goroutine 378 [running]:
code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh.generateKeys(0x1ee3540, 0x1, 0x1, 0x1ee3541, 0x1, 0x1, 0x1ee3542, 0x1, 0x1, 0xc4209f8260, ...)
	/srv/app/src/code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh/transport.go:201 +0x141
code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh.newPacketCipher(0x1ee3540, 0x1, 0x1, 0x1ee3541, 0x1, 0x1, 0x1ee3542, 0x1, 0x1, 0xc4209f8260, ...)
	/srv/app/src/code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh/transport.go:213 +0x98
code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh.(*transport).prepareKeyChange(0xc420d86c00, 0xc4210e6480, 0xc4210e6f00, 0xc4210e6480, 0xc4210e2000)
	/srv/app/src/code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh/transport.go:72 +0xd9
code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh.(*handshakeTransport).enterKeyExchangeLocked(0xc4210b8000, 0xc4207d4c00, 0x588, 0x588, 0x0, 0x0)
	/srv/app/src/code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh/handshake.go:412 +0x41c
code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh.(*handshakeTransport).readOnePacket(0xc4210b8000, 0x14d17e0, 0x2, 0xffffffffffffffff, 0x0, 0xc420908fc8)
	/srv/app/src/code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh/handshake.go:179 +0xf8
code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh.(*handshakeTransport).readLoop(0xc4210b8000)
	/srv/app/src/code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh/handshake.go:129 +0x2f
created by code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh.newServerTransport
	/srv/app/src/code.gitea.io/gitea/vendor/golang.org/x/crypto/ssh/handshake.go:104 +0x1c7
```

**Comment by pztrn** [comment]
Updated description - pull is also failing.

**Comment by lafriks** [comment]
Are you using about built-in ssh server?

**Comment by pztrn** [comment]
Yes.

**Comment by lafriks** [comment]
I was able to reproduce this error
