### ISSUE TITLE
Failure to execute `make generate-swagger` in go 1.22

### ISSUE THREAD

**Issue by sillyguodong** [go-gitea/gitea#29664]
### Description

After deleting `v1_json.tmpl`, I tried to execute `make generate-swagger` to re-generate the swagger file, but it failed. 
![image](https://github.com/go-gitea/gitea/assets/33891828/c89b1f79-b3fc-4f9f-b0b5-61013978f18b)

### Question
1. Do I need to delete this file before re-generating it?
2. If the file is not deleted and the command line is executed directly, it only returns: make: Nothing to be done for `generate-swagger'. However, I have actually added some new APIs and comment for them

### Gitea Version

9dc8a6336edddca0f3f90392bbc398f4ceaeaf13

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by silverwind** [comment]
I think I've dealt with this before. Try excluding some unneccesary directories when running it:

```
init --exclude web_src,node_modules,,.venv,.air
```

**Comment by silverwind** [comment]
> Do I need to delete this file before re-generating it?

No, it will be overwritten

> If the file is not deleted and the command line is executed directly, it only returns: make: Nothing to be done for `generate-swagger'. However, I have actually added some new APIs and comment for them

This is make dependency tracking in action. If there is no change in any `.go` file, we do not need to run swagger. Change a go file to get it running.

**Comment by silverwind** [comment]
That said, it also crashes for me. Maybe it's related to golang, I run with 1.22.1 currently:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100eeb494]

goroutine 294 [running]:
go/types.(*Checker).handleBailout(0x140015d6200, 0x1400133fb98)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/check.go:367 +0x9c
panic({0x1013b6860?, 0x101a20f20?})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/panic.go:770 +0x124
go/types.(*StdSizes).Sizeof(0x0, {0x1014a6c98, 0x101a2bda0})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/sizes.go:228 +0x314
go/types.(*Config).sizeof(...)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/sizes.go:333
go/types.representableConst.func1({0x1014a6c98?, 0x101a2bda0?})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/const.go:76 +0x9c
go/types.representableConst({0x1014ab980, 0x101a5e180}, 0x140015d6200, 0x101a2bda0, 0x0)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/const.go:92 +0x138
go/types.(*Checker).arrayLength(0x140015d6200, {0x1014a9520, 0x140015de820?})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/typexpr.go:510 +0x238
go/types.(*Checker).typInternal(0x140015d6200, {0x1014a9430, 0x140015e05a0}, 0x0)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/typexpr.go:299 +0x3bc
go/types.(*Checker).definedType(0x140015d6200, {0x1014a9430, 0x140015e05a0}, 0x1400133f158?)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/typexpr.go:180 +0x2c
go/types.(*Checker).varType(0x140015d6200, {0x1014a9430, 0x140015e05a0})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/typexpr.go:145 +0x2c
go/types.(*Checker).structType(0x140015d6200, 0x140015e0900, 0x140015e0900?)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/struct.go:113 +0x128
go/types.(*Checker).typInternal(0x140015d6200, {0x1014aa060, 0x14001583c50}, 0x140015c75e0)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/typexpr.go:316 +0xed0
go/types.(*Checker).definedType(0x140015d6200, {0x1014aa060, 0x14001583c50}, 0x1008ac124?)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/typexpr.go:180 +0x2c
go/types.(*Checker).typeDecl(0x140015d6200, 0x140015c75e0, 0x14000e306c0, 0x0)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/decl.go:615 +0x39c
go/types.(*Checker).objDecl(0x140015d6200, {0x1014b1ce0, 0x140015c75e0}, 0x0)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/decl.go:197 +0x880
go/types.(*Checker).packageObjects(0x140015d6200)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/resolver.go:681 +0x3c0
go/types.(*Checker).checkFiles(0x140015d6200, {0x140015b2270, 0x1, 0x1})
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/check.go:408 +0x164
go/types.(*Checker).Files(...)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0x140000e08c0, 0x140010cb260)
	/Users/silverwind/go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:1055 +0x870
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
	/Users/silverwind/go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:854 +0x178
sync.(*Once).doSlow(0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
	/opt/homebrew/Cellar/go/1.22.1/libexec/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
	/Users/silverwind/go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:842 +0x50
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
	/Users/silverwind/go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:849 +0x30
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 293
	/Users/silverwind/go/pkg/mod/golang.org/x/tools@v0.9.3/go/packages/packages.go:848 +0x84
exit status 2
```

**Comment by silverwind** [comment]
Upstream bug: https://github.com/go-swagger/go-swagger/issues/3070

**Comment by silverwind** [comment]
Workaround is likely to downgrade go to 1.21 until upstream has fixed it.

**Comment by silverwind** [comment]
https://github.com/go-gitea/gitea/pull/29780
