### ISSUE TITLE
Repo Topic Containing Backslash Leads to Javascript Error

### ISSUE THREAD

**Issue by kdumontnu** [go-gitea/gitea#31328]
### Description

If you create a repo topic with a backslash you receive the following javascript error:

```
Error: Syntax error, unrecognized expression: [data-value="test\"]
    at Ha.error (jquery.js:1487:8)
    at Tu (jquery.js:2153:8)
    at Cc (jquery.js:2578:12)
```
It's unclear if this is getting through some escape code or if this indicates a larger issue.

To recreate, go to a repository -> manage topics -> "test\" -> Enter

### Gitea Version

gitea.com

### Can you reproduce the bug on the Gitea demo site?

Yes

### Screenshots

<img width="998" alt="Screenshot 2024-06-11 at 5 41 41 PM" src="https://github.com/go-gitea/gitea/assets/12700993/72488239-fdda-4923-a1a6-318aa7999166">

### How are you running Gitea?

gitea.com

### Database

None

**Comment by silverwind** [comment]
Seems like a bug in Fomantic-UI based on that stack trace. Likely missing `CSS.escape` somewhere. Given that we are not updating Fomantic-UI anymore, we need a alternative for this tag entry.

<img width="597" alt="image" src="https://github.com/go-gitea/gitea/assets/115237/21130481-08c4-4894-9323-05808f2bb96e">

**Comment by wxiaoguang** [comment]
Actually `/` is not supported:


![image](https://github.com/go-gitea/gitea/assets/2114189/a85466cb-adfb-41ac-9e8d-693311021faa)

**Comment by silverwind** [comment]
I guess we could move the remaining fomantic source files to editable first-party files. Been meaning to to that for at least the CSS files, but also possible for the JS.

**Comment by wxiaoguang** [comment]
->  Fix varioius Fomantic UI problems #33851
