### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'textEdited') at Object.<anonymous> (repo-issue-content.js:123:32)

### ISSUE THREAD

**Issue by netsrotr** [go-gitea/gitea#32047]
### Description

Gitea Version: 1.21.4
I had one of our issues open within Chrome and installed a pending chrome update. Chrome opened the last browser tabs again and I received an error message at top the issues display page: 
`JavaScript error: Uncaught TypeError: Cannot read properties of undefined (reading 'textEdited') (https://git.our-server.de/assets/js/index.js?v=1.21.4 @ 53:664). Open browser console to see more details.`

Details from browser dev console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'textEdited') 
    at Object.<anonymous> (repo-issue-content.js:123:32) 
    at Pe (jquery.js:3223:31) 
    at Object.fireWith [as resolveWith] (jquery.js:3353:7) 
    at os (jquery.js:9627:14) 
    at XMLHttpRequest.<anonymous> (jquery.js:9888:9)  
11:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

### Gitea Version

1.21.4

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

using a pre-build package to host it on Ubuntu

### Database

None

**Comment by lunny** [comment]
Please upgrade to 1.22.2 to take a look at whether it has been fixed.

**Comment by wxiaoguang** [comment]
It should have been fixed
