### ISSUE TITLE
FreeBSD problem

### ISSUE THREAD

**Issue by gudvindll** [go-gitea/gitea#3700]
- Gitea version (or commit ref): 1.4.0-rc3
- Git version: git version 2.13.0
- Operating system: FreeBSD 11.1
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

 ```
go get -d -u code.gitea.io/gitea
 cd ******code.gitea.io/

ls
.changelog.yml  .gitattributes  assets          CONTRIBUTING.md Dockerfile      main.go         modules         README_ZH.md    templates
.drone.yml      .github         CHANGELOG.md    custom          docs            MAINTAINERS     options         README.md       vendor
.editorconfig   .gitignore      cmd             DCO             integrations    Makefile        package.json    routers
.git            .lgtm           contrib         docker          LICENSE         models          public          scripts


 git tag -l
v0.9.99
v1.0.0
v1.0.1
v1.0.2
v1.1.0
v1.1.1
v1.1.2
v1.1.3
v1.1.4
v1.2.0
v1.2.0-rc1
v1.2.0-rc2
v1.2.0-rc3
v1.2.1
v1.2.2
v1.2.3
v1.3.0
v1.3.0-rc1
v1.3.0-rc2
v1.3.1
v1.3.2
v1.3.3
v1.4.0-rc1
v1.4.0-rc2
v1.4.0-rc3
root@web:~/go/src/code.gitea.io/gitea # git checkout v1.4.0-rc3
Previous HEAD position was 68134e64... Escape branch name in dropdown menu (#3692)
HEAD is now at 30226814... Changelog for 1.4.0-rc3 (#3679)
root@web:~/go/src/code.gitea.io/gitea # make generate build
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 7: Missing dependency operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 9: Need an operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 15: Need an operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 42: Missing dependency operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 43: warning: duplicate script for target "ifeq" ignored
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 8: warning: using previous script for "ifeq" defined here
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 43: warning: duplicate script for target "(,)" ignored
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 8: warning: using previous script for "(,)" defined here
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 43: warning: duplicate script for target "(Windows_NT)" ignored
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 8: warning: using previous script for "(Windows_NT)" defined here
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 44: Need an operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 46: Need an operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 48: Missing dependency operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 49: warning: duplicate script for target "(,)" ignored
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 8: warning: using previous script for "(,)" defined here
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 50: Need an operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 56: Need an operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 236: Missing dependency operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 237: warning: duplicate script for target "ifeq" ignored
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 8: warning: using previous script for "ifeq" defined here
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 238: Need an operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 246: Missing dependency operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 247: warning: duplicate script for target "ifeq" ignored
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 8: warning: using previous script for "ifeq" defined here
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 247: warning: duplicate script for target "(,drone)" ignored
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 237: warning: using previous script for "(,drone)" defined here
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 248: Need an operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 256: Missing dependency operator
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 257: warning: duplicate script for target "ifeq" ignored
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 8: warning: using previous script for "ifeq" defined here
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 257: warning: duplicate script for target "(,drone)" ignored
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 237: warning: using previous script for "(,drone)" defined here
make: "/root/go/src/code.gitea.io/gitea/Makefile" line 258: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /root/go/src/code.gitea.io/gitea

```

var 2

```
root@web:~ # pkg install gitea
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 2 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        gitea: 1.3.3
        bash: 4.4.19
*********************************************************
===> Creating groups.
Creating group 'git' with gid '211'.
===> Creating users
Creating user 'git' with uid '211'.
[web] [2/2] Extracting gitea-1.3.3: 100%
root@web:~ # gitea web
2018/03/21 09:47:11 [W] Custom config '/usr/local/sbin/custom/conf/app.ini' not found, ignore this if you're running first time
2018/03/21 09:47:11 [T] AppPath: /usr/local/sbin/gitea
2018/03/21 09:47:11 [T] AppWorkPath: /usr/local/sbin
2018/03/21 09:47:11 [T] Custom path: /usr/local/sbin/custom
2018/03/21 09:47:11 [T] Log path: /usr/local/sbin/log
2018/03/21 09:47:11 [I] Gitea v1.3.3
2018/03/21 09:47:11 [I] Log Mode: Console(Trace)
2018/03/21 09:47:11 [I] XORM Log Mode: Console(Trace)
2018/03/21 09:47:11 [I] Cache Service Enabled
2018/03/21 09:47:11 [I] Session Service Enabled
2018/03/21 09:47:11 [I] SQLite3 Supported
2018/03/21 09:47:11 [I] Run Mode: Development
panic: fail to set message file(en-US): open conf/locale/locale_en-US.ini: no such file or directory

goroutine 1 [running]:
code.gitea.io/gitea/vendor/github.com/go-macaron/i18n.initLocales(0xc420277375, 0x0, 0x1147c23, 0xb, 0xc42025bf80, 0x1153169, 0x12, 0xc420104c60, 0x15, 0x15, ...)
        /wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/vendor/github.com/go-macaron/i18n/i18n.go:57 +0x764
code.gitea.io/gitea/vendor/github.com/go-macaron/i18n.I18n(0xc4202840c0, 0x1, 0x1, 0x0, 0x0)
        /wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/vendor/github.com/go-macaron/i18n/i18n.go:158 +0xcb
code.gitea.io/gitea/routers/routes.NewMacaron(0xc420247e00)
        /wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/routers/routes/routes.go:93 +0x6ef
code.gitea.io/gitea/cmd.runWeb(0xc420247e00, 0x0, 0x0)
        /wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/cmd/web.go:67 +0xb2
code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0xfc6800, 0x118e9b8, 0xc420247e00, 0xc42008d500, 0x0)
        /wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xad
code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x113bc7c, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1159519, 0x16, 0x0, ...)
        /wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0xa0e
code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc42009f1e0, 0xc4200b0000, 0x2, 0x2, 0x0, 0x0)
        /wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x5b8
main.main()
        /wrkdirs/usr/ports/www/gitea/work/src/code.gitea.io/gitea/main.go:48 +0x383

```

how install gitea on FreeBSD?

**Comment by gudvindll** [comment]
sysrc gitea_enable=YES
service gitea start
but i have such a problem
```
root@web:confused: # service gitea start
daemon: illegal option -- S
usage: daemon [-cfr] [-p child_pidfile] [-P supervisor_pidfile]
[-t title] [-u user] command arguments ...
```
```
gitea_start() {
        /usr/sbin/daemon -S -l ${gitea_facility} -s ${gitea_priority} -t ${name} \
                -u ${gitea_user} -p ${pidfile} \
                /usr/bin/env -i \
                "GITEA_WORK_DIR=${gitea_shared}" \
                "GITEA_CUSTOM=/usr/local/etc/${name}" \
                "HOME=${githome}" \
                "PATH=/usr/local/bin:${PATH}" \
                "USER=git" \
                $command
```
tags -S -l -s illegal for FreeBSD

```
root@web:/ # service gitea start
root@web:/ # 2018/03/21 13:32:03 [T] AppPath: /usr/local/sbin/gitea
2018/03/21 13:32:03 [T] AppWorkPath: /usr/local/share/gitea
2018/03/21 13:32:03 [T] Custom path: /usr/local/etc/gitea
2018/03/21 13:32:03 [T] Log path: /var/log/gitea
2018/03/21 13:32:03 [I] Gitea v1.3.3
2018/03/21 13:32:15 Serving 127.0.0.1:3000 with pid 94434
```
but is don't work i could not connect to ip_address:3000

**Comment by gudvindll** [comment]
change ip addres in app.ini to 0.0.0.0 and it work

**Comment by gudvindll** [comment]
# #
