### ISSUE TITLE
Missing close tags in U2F in sample

### ISSUE THREAD

**Issue by francoism90** [go-gitea/gitea#4255]
- Gitea version (or commit ref): master
- Git version: latest commit
- Operating system: Arch Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
```
[U2F]
; Two Factor authentication with security keys
; https://developers.yubico.com/U2F/App_ID.html
APP_ID = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s
; Comma seperated list of truisted facets
TRUSTED_FACETS = %(PROTOCOL)s://%(DOMAIN)s:%(HTTP_PORT)s
```

**Comment by francoism90** [comment]
Hmm, it seems the issue is bigger, I need to comment everything in that block, otherwise I'll receive the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7bfc73]

goroutine 1 [running]:
code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).transformValue(0xc4205c7aa0, 0xc4205bb741, 0x28, 0xc42051ee58, 0x4abbc9)
        /home/archie/gitea-git/src/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:123 +0xa3
code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).String(0xc4205c7aa0, 0xc4205cc260, 0x15)
        /home/archie/gitea-git/src/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:130 +0x3d
code.gitea.io/gitea/vendor/gopkg.in/ini%2ev1.(*Key).MustString(0xc4205c7aa0, 0xc4205cc260, 0x15, 0x1, 0xc4205cc260)
        /home/archie/gitea-git/src/src/code.gitea.io/gitea/vendor/gopkg.in/ini.v1/key.go:202 +0x2f
code.gitea.io/gitea/modules/setting.NewContext()
        /home/archie/gitea-git/src/src/code.gitea.io/gitea/modules/setting/setting.go:1147 +0x444a
code.gitea.io/gitea/routers.GlobalInit()
        /home/archie/gitea-git/src/src/code.gitea.io/gitea/routers/init.go:47 +0x4a
code.gitea.io/gitea/cmd.runWeb(0xc4205a43c0, 0x0, 0x0)
        /home/archie/gitea-git/src/src/code.gitea.io/gitea/cmd/web.go:83 +0xa8
code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0x1412f00, 0x16ef910, 0xc4205a43c0, 0xc42034d700, 0x0)
        /home/archie/gitea-git/src/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xad
code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x164cc4a, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1670974, 0x16, 0x0, ...)
        /home/archie/gitea-git/src/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0xa0e
code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc42059c1a0, 0xc42003a0c0, 0x4, 0x4, 0x0, 0x0)
        /home/archie/gitea-git/src/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x5b8
main.main()
        /home/archie/gitea-git/src/src/code.gitea.io/gitea/main.go:52 +0x40e
```

Something is going wrong with `make` - seems it doesn't setup the correct path. Note: `home/archie/gitea-git/src/src/code.gitea.io/gitea` is the compile path.
