### ISSUE TITLE
Getting Internal Server error 500 on install

### ISSUE THREAD

**Issue by MayhemBill** [go-gitea/gitea#7546]
- Gitea version (or commit ref): 1.9.0+rc2-4-g3fd07a0be (and 1.10 from master dl folder)
- Git version: 2.7.4
- Operating system: Ubuntu 16.04 WSL
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description

I get a 500 error when I try to install gitea, I have tried several versions of the app and both produce the same outcome:

```
invalid page type: 0: 4
/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/cursor.go:250 (0xf44463)
/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/cursor.go:159 (0xf43a6d)
/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/bucket.go:105 (0xf3f994)
/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/tx.go:101 (0xf7a54c)
/go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/store/boltdb/store.go:123 (0xf7a521)
/go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:315 (0xeaa525)
/go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index_impl.go:108 (0xfcc424)
/go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.go:255 (0x129052a)
/go/src/code.gitea.io/gitea/modules/indexer/issues/bleve.go:142 (0x12904c6)
/go/src/code.gitea.io/gitea/modules/indexer/issues/bleve.go:183 (0x1290826)
/go/src/code.gitea.io/gitea/modules/indexer/issues/indexer.go:62 (0x1291b3f)
/go/src/code.gitea.io/gitea/routers/init.go:97 (0x142fd02)
/go/src/code.gitea.io/gitea/routers/install.go:358 (0x143365f)
/usr/local/go/src/reflect/value.go:447 (0x48f370)
/usr/local/go/src/reflect/value.go:308 (0x48edf3)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x985496)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x984d8b)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x9b4f09)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x11d1fa8)
/go/src/code.gitea.io/gitea/modules/context/panic.go:38 (0x11d1f9b)
/usr/local/go/src/reflect/value.go:447 (0x48f370)
/usr/local/go/src/reflect/value.go:308 (0x48edf3)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:177 (0x985496)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:137 (0x984d8b)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x9b4f09)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x9e46e6)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/session/session.go:192 (0x9e46d1)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:79 (0x9b4db0)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x985150)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x984e7a)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x9b4f09)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x9c699f)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x9c698d)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:40 (0x9b8ba3)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x985150)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x984e7a)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x9b4f09)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:112 (0x9c5cc0)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:52 (0x9c5cab)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/logger.go:40 (0x9b8ba3)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:157 (0x985150)
/go/src/code.gitea.io/gitea/vendor/github.com/go-macaron/inject/inject.go:135 (0x984e7a)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/context.go:121 (0x9b4f09)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:187 (0x9c7be6)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/router.go:294 (0x9c16fd)
/go/src/code.gitea.io/gitea/vendor/gopkg.in/macaron.v1/macaron.go:220 (0x9b9f7c)
/go/src/code.gitea.io/gitea/vendor/github.com/gorilla/context/context.go:141 (0xd18a3a)
/usr/local/go/src/net/http/server.go:1995 (0x779a53)
/usr/local/go/src/net/http/server.go:2774 (0x77cd27)
/usr/local/go/src/net/http/server.go:1878 (0x778a10)
/usr/local/go/src/runtime/asm_amd64.s:1337 (0x464680)
```

Upon trying to login with the account I created, it tells me the password is incorrect, even though I know that it is not. (after the first instance of this happening I just set the password to 1234 to test it.)

##Edit

It seems if I create an account after the fact, it does become user #1, and I have site administration.

**Comment by MayhemBill** [comment]
If I stop the gitea process, I get the above error in console upon the next start up.

**Comment by MayhemBill** [comment]
This does not happen however if I run the windows version of gitea

**Comment by lunny** [comment]
I have no WSL to test it. It should upstream library's problem (bleve or bbolt).

**Comment by MayhemBill** [comment]
upon a google search for the issue, it is a bolt issue.

**Comment by fieldinrain** [comment]
the same error occurred when I install gitea on wsl.
gitea: 1.11.0
git: 2.17.1
```
panic: invalid page type: 0: 4

goroutine 2345 [running]:
code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt.(*Cursor).search(0xc003e4da60, 0xc003e4dac0, 0x5, 0x20, 0x4)
        /go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/cursor.go:250 +0x353
code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt.(*Cursor).seek(0xc003e4da60, 0xc003e4dac0, 0x5, 0x20, 0x0, 0x0, 0x0, 0x1, 0xc0039c3390, 0x0, ...)
        /go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/cursor.go:159 +0x7d
code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt.(*Bucket).Bucket(0xc0001547f8, 0xc003e4dac0, 0x5, 0x20, 0x5)
        /go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/bucket.go:105 +0xd4
code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt.(*Tx).Bucket(...)
        /go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/tx.go:101
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/store/boltdb.(*Store).Reader(0xc003dc69b0, 0x456dea0, 0xc003e565a0, 0x3315600, 0xc003dc69b0)
        /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/store/boltdb/store.go:123 +0xac
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Open(0xc0064b2a80, 0x0, 0x0)
        /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:315 +0x15f
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve.newIndexUsing(0xc003b5c100, 0x34, 0x332b200, 0xc0064b2a00, 0x1e75e15, 0xb, 0x1e66c40, 0x6, 0x0, 0x0, ...)
        /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index_impl.go:109 +0x4ab
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve.New(...)
        /go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.go:257
code.gitea.io/gitea/modules/indexer/issues.createIssueIndexer(0xc003b5c100, 0x34, 0x1, 0x0, 0x0, 0x0, 0x0)
        /go/src/code.gitea.io/gitea/modules/indexer/issues/bleve.go:143 +0x6ac
code.gitea.io/gitea/modules/indexer/issues.(*BleveIndexer).Init(0xc003dc11c0, 0xc003dc11c0, 0xc0000d2000, 0x7f34b5a51460)
        /go/src/code.gitea.io/gitea/modules/indexer/issues/bleve.go:184 +0xa7
code.gitea.io/gitea/modules/indexer/issues.InitIssueIndexer.func2.1(0xc006a98ed0, 0xc006a98ef0)
        /go/src/code.gitea.io/gitea/modules/indexer/issues/indexer.go:148 +0x83
code.gitea.io/gitea/modules/graceful.(*Manager).RunWithShutdownFns(0xc000086f60, 0xc00173ffb0)
        /go/src/code.gitea.io/gitea/modules/graceful/manager.go:77 +0xf6
code.gitea.io/gitea/modules/indexer/issues.InitIssueIndexer.func2(0x2e84b00, 0xc006a50300)
        /go/src/code.gitea.io/gitea/modules/indexer/issues/indexer.go:146 +0x412
created by code.gitea.io/gitea/modules/indexer/issues.InitIssueIndexer
        /go/src/code.gitea.io/gitea/modules/indexer/issues/indexer.go:140 +0xc7
```
