### ISSUE TITLE
"This site can’t be reached" when create Pull Request

### ISSUE THREAD

**Issue by mesquitamv** [go-gitea/gitea#9663]
- Gitea version (or commit ref): 1.10.2 (Docker) (https://hub.docker.com/layers/gitea/gitea/1.10.2/images/sha256-6840e92bfa48a789294017205e56aa23aa4ad2dafaa3c0cfad32f26e4ea73794)
- Git version: 2.22.2
- Database:
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes
  - [X] No
  - [ ] Not relevant

## Description
Every time when I create a pull request in a repository that have 100+ commits I get "This site can’t be reached" error on browser, and after 10, 15 seconds if I refresh the page, Gitea answer 200 to me and show the pull request page that I created.

When I create a PR, this message is shown in Docker log:

```
[Macaron] 2020-01-09 11:45:40: Started GET /api/v1/repos/xxxxx/xxxxxxxxxx/raw/66e7d72c0114caa2076fa4522b38d65c11423e94/Jenkinsfile for 10.255.0.2

panic: page 1116 already freed

goroutine 88 [running]:

github.com/etcd-io/bbolt.(*freelist).free(0xc001b38a00, 0xb34, 0x7f2a787bb000)
	/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/freelist.go:175 +0x3d4
github.com/etcd-io/bbolt.(*node).spill(0xc008721c00, 0xc008c5fc80, 0x20)
	/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/node.go:363 +0x206
github.com/etcd-io/bbolt.(*node).spill(0xc008721b90, 0xc008c5fc60, 0x20)
	/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/node.go:350 +0xba
github.com/etcd-io/bbolt.(*node).spill(0xc008721b20, 0xc008c43650, 0xc009758e08)
	/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/node.go:350 +0xba
github.com/etcd-io/bbolt.(*Bucket).spill(0xc00402b100, 0xc008c43500, 0xc009759000)
	/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/bucket.go:568 +0x473
github.com/etcd-io/bbolt.(*Bucket).spill(0xc0086955f8, 0x4ad89947d6, 0x4005800)
	/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/bucket.go:535 +0x3d5
github.com/etcd-io/bbolt.(*Tx).Commit(0xc0086955e0, 0xc009759268, 0xc0097591a8)
	/go/src/code.gitea.io/gitea/vendor/github.com/etcd-io/bbolt/tx.go:160 +0xec
github.com/blevesearch/bleve/index/store/boltdb.(*Writer).ExecuteBatch.func1(0xc009759360, 0xc0086955e0)
	/go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/store/boltdb/writer.go:52 +0x4e
github.com/blevesearch/bleve/index/store/boltdb.(*Writer).ExecuteBatch(0xc009379eb0, 0x31a6200, 0xc008c5e2c0, 0x0, 0x0)
	/go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/store/boltdb/writer.go:90 +0x51f
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).batchRows(0xc001b38980, 0x31a1cc0, 0xc009379eb0, 0xc008c5e260, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:292 +0x7ee
github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Batch(0xc001b38980, 0xc008732ac0, 0xc008bec04c, 0x3)
	/go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:940 +0x123f
github.com/blevesearch/bleve.(*indexImpl).Batch(0xc0008ad420, 0xc008c64000, 0x0, 0x0)
	/go/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index_impl.go:309 +0x9c
github.com/ethantkoenig/rupture.(*singleIndexFlushingBatch).Flush(0xc008732ae0, 0xc008bec04c, 0x3)
	/go/src/code.gitea.io/gitea/vendor/github.com/ethantkoenig/rupture/flushing_batch.go:61 +0x41
code.gitea.io/gitea/modules/indexer/issues.(*BleveIndexer).Index(0xc001b2bb20, 0xc0018901e0, 0x1, 0x14, 0xc008bde800, 0x1)
	/go/src/code.gitea.io/gitea/modules/indexer/issues/bleve.go:205 +0x239
code.gitea.io/gitea/modules/indexer/issues.(*LevelQueue).Run(0xc0019d2540, 0x0, 0x0)
	/go/src/code.gitea.io/gitea/modules/indexer/issues/queue_disk.go:48 +0x97
code.gitea.io/gitea/modules/indexer/issues.InitIssueIndexer.func1(0xc001ba87d0)
	/go/src/code.gitea.io/gitea/modules/indexer/issues/indexer.go:105 +0x39
created by code.gitea.io/gitea/modules/indexer/issues.InitIssueIndexer
	/go/src/code.gitea.io/gitea/modules/indexer/issues/indexer.go:104 +0x2a9


Nothing is shown on Browser console.
...

**Comment by zeripath** [comment]
So weirdly this looks like a double free causing a panic from within the indexer.

Hmm...

Setting the Log level to trace should tell you that the data being sent to the indexer is reasonable but I don't think it is that.

Are there any logs before this panic indicating an error?

**Comment by MarcusVMesquita** [comment]
Hi,

I solved the problem. I had to delete `/data/gitea/indexers` directory for Gitea recreate all index. After that the problem was solved.

Thanks
